### ISSUE TITLE
Bulk Download and Filename

### ISSUE THREAD

**Issue by stratox7** [HuiiBuh/InstagramDownloader#100]
Is it possible to enhance the code with saving the bulk download .rar file with the account that is being saved username; as well as the individual content beiong saved within?

Regards.

**Comment by HuiiBuh** [comment]
Are there any advantages to saving the images un a rar file?
If not I am not going to implement that feature.

As for the account name as file name. The idea is good and I will implement it when I find the time to do it.

**Comment by stratox7** [comment]
It doesn't have to be a rar file. Just a compressed file format; .rar and .zip seem to the most prevalent. For me its more of a organizational enhancment. Sometimes we simple humans forget things. lol

Thanks.

**Comment by HuiiBuh** [comment]
It is already ziped

**Comment by HuiiBuh** [comment]
The bulk download now has the account name
