### ISSUE TITLE
Maximize image instead of downloading

### ISSUE THREAD

**Issue by killerz298** [HuiiBuh/InstagramDownloader#101]
I used to use a script while allowed me to open the photo full size without downloading but it no longer works. As your extension already knows the link for the full size image, is there any way to implement into the extension the ability to view the image maximized instead of downloading? Perhaps make it so when you click the image it opens maximized or something like that?

**Comment by HuiiBuh** [comment]
If you want that feature you can create a pull request.
I don't use the extension any more and only create bug fixes.
