### ISSUE TITLE
Download Saved Objects

### ISSUE THREAD

**Issue by splitbrainCH** [HuiiBuh/InstagramDownloader#102]
Hi!

I love your extension - thank you for writing it! There is just one thing that I would wish it had:

Could you integrate the "Download All"-Button on the "Saved"-Page like you have it on a specific Userprofile? My guess form the design and a quick view over the HTML is, that these pages are quite similar. Also the pagination-Loading is needed on both pages.

This is the page I'm talking about: https://www.instagram.com/<YOUR-USERNAME>/saved/

Thank you for considering adding this feature :-)
Rolf

**Comment by HuiiBuh** [comment]
That is a good idea. I will give it a try if I can find the time.

**Comment by HuiiBuh** [comment]
Just implemented the result of this command?

`document.getElementsByClassName("vBF20 _1OSdk")`
