### ISSUE TITLE
"Download All" Not working if already following

### ISSUE THREAD

**Issue by zxfrank** [HuiiBuh/InstagramDownloader#104]
The "follow" button is replaced by "Message" then the Download all is not added to the DOM.

**To Reproduce** go to any account you follow.
I copied the html from a Follow button and replaced it in the dom, the download all showed up

Firefox 82.0.3 (64-bit) on Xubuntu 18.04

**Comment by HuiiBuh** [comment]
I am sorry but I can't reproduce the bug. 
![image](https://user-images.githubusercontent.com/46561026/98978466-4f046e80-251a-11eb-8a6d-c2932a4c3a61.png)

**Comment by zxfrank** [comment]
![image](https://user-images.githubusercontent.com/1887075/98978740-6a568600-24e8-11eb-9019-2e807c2f2064.png)

**Comment by HuiiBuh** [comment]
This is interesting. 
Could you please provide some additional information (Browser + Version + Screen Resolution)?

**Comment by zxfrank** [comment]
Firefox 82.0.3 (64-bit) on Xubuntu 18.04, the result is the same on any window size.

I think the button is outputted but disapears before the page completes to load...

**Comment by HuiiBuh** [comment]
This is nearly impossible because my extension listens to dom changes and reapplies the changes made by the extension. 
So I think the issue must be another one.

**Comment by HuiiBuh** [comment]
Could you send me the output of this command
`document.getElementsByClassName("vBF20 _1OSdk")`

**Comment by zxfrank** [comment]
![image](https://user-images.githubusercontent.com/1887075/98981807-75abb080-24ec-11eb-85f2-cf0060bb93db.png)

**Comment by HuiiBuh** [comment]
`document.querySelector(".nZSzR").innerHTML`

**Comment by zxfrank** [comment]
I was about to do nearly the same :P

```
<h2 class="_7UhW9 fKFbl yUEEX KV-D4 fDxYl ">account_name</h2>
<div class=" Igw0E IwRSH eGOV_ _4EzTm soMvl ">
<span class="mTLOB Szr5J coreSpriteVerifiedBadge " title="Verified">Verified</span>
</div>
<div class=" Igw0E IwRSH eGOV_ ybXk5 _4EzTm ">
<div class=" Igw0E IwRSH eGOV_ ybXk5 _4EzTm ">
<div class="_862NM ">
<div class=" Igw0E IwRSH eGOV_ vwCYk JI_ht ">
<button class="sqdOP L3NKy _4pI4F _8A5w5 " type="button">Message</button>
</div>
</div>
<div class=" ">
<button class="sqdOP L3NKy _8A5w5 " type="button">
<div class=" Igw0E rBNOH YBx95 _4EzTm " style="height: 18px;">
<span aria-label="Following" class="glyphsSpriteFriend_Follow u-__7">
</span>
</div>
</button>
</div>
</div>
</div>
<div class="AFWDX">
<button class="wpO6b " type="button">
<div class="QBdPU ">
<svg aria-label="Options" class="_8-yf5 " fill="#262626" height="24" viewBox="0 0 48 48" width="24">
<circle clip-rule="evenodd" cx="8" cy="24" fill-rule="evenodd" r="4.5">
</circle>
<circle clip-rule="evenodd" cx="24" cy="24" fill-rule="evenodd" r="4.5">
</circle>
<circle clip-rule="evenodd" cx="40" cy="24" fill-rule="evenodd" r="4.5">
</circle>
</svg>
</div>
</button>
</div>
```

**Comment by HuiiBuh** [comment]
Thanks I could not reproduce the issue, but the button should be on its pace now.
You can checkout the master branch to see if it is working

**Comment by HuiiBuh** [comment]
Just updated it. 
Could you please confirm that Version 3.4.1 does not have your bug?

**Comment by zxfrank** [comment]
nailed it!
thanks!
