### ISSUE TITLE
Video download stopped working

### ISSUE THREAD

**Issue by Halvar10** [HuiiBuh/InstagramDownloader#109]
**Describe the bug**
Two or three days ago, video download mysteriously stopped working for me. For pictures, everything works as before,, but for videos, I click the download button and nothing happens at all. Doesn't matter if I click the button directly on the feed or in details view.

**To Reproduce**
1. Go to any video entry on Instagram
2. Click on the download button. 
3. Nothing happens, also no error message in the JS console.

**Desktop (please complete the following information):**
 - Resolution: 2K 
 - Browser Firefox 83.0 x64 on Windows 10.
 - InstagramDownloader version 3.4.1, last updated November 12, 2020, 

**Additional context**
This has worked for a long time on my computer, thanks for writing and still supporting this!

**Comment by kebera** [comment]
Installed because "Save as" from Media tab stopped working yesterday. This addon is also not working.  Videos are now shown through some kind of inline player and the url is a blob instead of a downloadable mpg file. 
Add-on works fine for images.
Firefox 78.5.0esr x64 on Linux.

**Comment by HuiiBuh** [comment]
Thanks for reporting.
I will dedicate some time to fixing it this weekend

**Comment by HuiiBuh** [comment]
Just finished the last work for Version 4.0.0

Make lots of changes under the hood, but mainly fixed the existing bugs. 

See [here](https://github.com/HuiiBuh/InstagramDownloader/releases/tag/v4.0.0) for more details.

**Comment by Halvar10** [comment]
Thank you thank you thank you, for not only keeping up with IG's shenanigans but even making the addon better.
