### ISSUE TITLE
browsing history permission?

### ISSUE THREAD

**Issue by SESNut** [HuiiBuh/InstagramDownloader#111]
Why does this suddenly require browsing history permission?

**Comment by HuiiBuh** [comment]
It does not.
It requires the tabs permission

See https://github.com/HuiiBuh/InstagramDownloader/blob/master/src/manifest_firefox.json

**Comment by HuiiBuh** [comment]
Perhaps this is a warning from chrome because it would be possible to monitor all browsing activity if you have the tabs permission.

The permission is only used to send messages from the background script to the content script

**Comment by HuiiBuh** [comment]
Don't you think it is a bit unnecessary to write a review in the chrome store and at the same time open an issue on github?

**Comment by SESNut** [comment]
I wasnt really sure where I'd get a response from if any.

**Comment by HuiiBuh** [comment]
No Problem. 
Next time just ask on Github. I should usually reply in less than a week
