### ISSUE TITLE
Download all doesn't finish, looks like stops on compression

### ISSUE THREAD

**Issue by azat11** [HuiiBuh/InstagramDownloader#114]
**Describe the bug**
460 posts, 637 media files. When compressing the blue sign informing of compression disappears and nothing happens afterwards. Might be connected to my PC running out of RAM, Waterfox uses up 3GB of it due to this download. (Checked it out ion Firefox too, does the same, uses about 2GB of RAM with one tab open. And checked it on Chrome, the same; RAM usage around 3GB.)

**To Reproduce**
1. Go to https://www.instagram.com/ginascarangella_/
2. Scroll down to the end
3. Go back to beginning of the page
4. Start download all
5. Confirm download
6. See compression sign disappear and nothing happen

**Desktop (please complete the following information):**
 - Resolution: 1366x768
 - Browser: Waterfox G3.0.2, Firefox 84.0, Chrome 87.0.4280.88

**Comment by azat11** [comment]
The compressing was just taking A LOT of time. After waiting a while the save window opens.

**Comment by HuiiBuh** [comment]
Jup. That is single threaded js ;D
