### ISSUE TITLE
Profile pic low quality download

### ISSUE THREAD

**Issue by auanasgheps** [HuiiBuh/InstagramDownloader#115]
**Describe the bug**
First of all I must congratulate with you because is the first time I see an open source Instagram extension. I found yours because the one I was using was flagged as malware and removed from the Chrome store, so I guess this time will be better. 

It's pretty hard to find a good product in this category, they're all made bad or don't work. I'm surprised I didn't know about this before.

Anyway, profile pictures are downloaded at 320x320, which is very low quality.

I noticed this very recently also with another website I am using to get photos because the previous extension didn't do this. So possibly this is a limit recently introduced in Instagram APIs?

**To Reproduce**
1. Download a profile picture from any profile
2. Observe is only 320x320 pixels.

**Expected behaviour**
Profile pictures should be downloaded at their native resolution (1000-ish x 1000-ish, like normal photos).

**Screenshots**

**Desktop (please complete the following information):**
 - Resolution: 1920x1080.
 - Browser: Chrome
 - Version 87, 64-bit.

**Comment by HuiiBuh** [comment]
Hi I would really like to fix that bug but unfortunately the highest resolution of the profile image I can get is 320x320.
If you have an idea how ito get a higher resolution image I would be glad to implement that method.

**Comment by HuiiBuh** [comment]
I am closing this because the highest resolution instagram provides is 320x320

**Comment by auanasgheps** [comment]
I have found an App which allows to get the full profile pic quality. It's this [one](https://play.google.com/store/apps/details?id=com.kimcy929.storysaver). 
Unfortunately it's not open source so we won't have a clue how it's doing it, but it works.

**Comment by HuiiBuh** [comment]
In what Resolution does this app download the profile picture

**Comment by auanasgheps** [comment]
I've just tried the account "Instagram" and is 1080x1080, hence I believe is in full quality.
