### ISSUE TITLE
IG stories downloads are cropped

### ISSUE THREAD

**Issue by highscreen** [HuiiBuh/InstagramDownloader#116]
Since a few days, the downloaded images from IG stories are cropped square.

**Comment by HuiiBuh** [comment]
I need more information (Browser, addon version, screen resolution,... =

**Comment by highscreen** [comment]
Sorry about that! let me know if anything else is needed.

Browser: Firefox 84.0.1
Addon version 3.4.1

Screen: 1440x900
MacOS 11.1

**Comment by HuiiBuh** [comment]
No problem.
I will have a look at your issue in the next few weeks

**Comment by HuiiBuh** [comment]
Just had a look at it and everything seems to work fine for me. 
Do you have an older version of the addon installed?

**Comment by highscreen** [comment]
Ah I didnt realise I wasn't on the latest version. I was still on 3.4.1. I just update to 4 and the issue seems to be gone! Sorry for the bother!
