### ISSUE TITLE
Download button

### ISSUE THREAD

**Issue by f0rr357** [HuiiBuh/InstagramDownloader#118]
When i open profile stories i can't see the download button which previously was left to the pause button, only a download all button on the lower left
i'm using lastest version, windows 10 firefox 84.0.1

**Comment by HuiiBuh** [comment]
The button is below the close button

**Comment by HuiiBuh** [comment]
if that is not thr problem please send me the url of the story. you have a. pribl. ihwt

**Comment by f0rr357** [comment]
My bad, extension wasn't active, thank you for the quick reply
