### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by rainblues** [HuiiBuh/InstagramDownloader#119]
The app still worked fine yesterday but today I couldn't download anything. Nothing works - neither the single-image button, nor the bulk downloader. I tried everything. I'm using Firefox and I tried to delete all cookies and temp data to see what happens but it still doesn't work. Then I tried to install the app on google chrome but it still doesn't work. What is happing?

**Comment by HuiiBuh** [comment]
Hi. 
There is a reason I have a issue template if you create a bug report. Could you please provide information like resolution, os, device and addon version so I can help you.#

Because for me it looks like everything is working correnctly

**Comment by Allen-Kwan** [comment]
I believe this happens when you download or scroll through too many pictures - if it's using the API to fetch links, it's either banning or returning some other error back instead of the image.

I'm not sure if there's a way to catch these errors and show them to the user?

**Comment by HuiiBuh** [comment]
Looks like rate limiting to me too.
I will close it, because there is nothing I can do about it

**Comment by HuiiBuh** [comment]
@Allen-Kwan 
I am planning to add some kind of error message and display it to the users, but this will take a while
