### ISSUE TITLE
Download All....Compressing...Nothing happens.

### ISSUE THREAD

**Issue by DEC1MU5** [HuiiBuh/InstagramDownloader#120]
**Describe the bug**
App appears to be working fine, until the end, when nothing happens and I cannot access the images.

**To Reproduce**
1 Click "Download All"
2. Clicked STOP to avoid being locked out from IG at 950 Images.
3. App Found all Images.
4. App says "Compressing images"
5. Nothing happens.

**Expected behaviour**
I would expect the zip to download automatically. Nothing happens. 
I would like to know where these images are temporarily stored and zipped, if I can just extract them manually the program right now will have utility for me, right now it doesn't.

**Screenshots**
Not applicable. 

**Desktop (please complete the following information):**
 - Resolution: 4k
 - Browser Chrome (Latest Build as well as Canary)

**Additional context**
I am requesting the temporary download location of the images to manually extract them.

**Comment by HuiiBuh** [comment]
If you download 900 images the compression can take quite a while. Perhaps you just have to wait for 1-2 hours.
I personally have not tried it for a long time and therefore don't know how long the compression will take.

I am afraid the files are not saved locally before compressing and a temporary download location does not exist for that reason.

I also cannot just save the files without zipping because the user would get spammed with 900 `save as` dialogs

**Comment by HuiiBuh** [comment]
Just had a Look at the api and it looks like I can save an image without creating a save as dialog.

However I think I cannot specify the download location which would mean that 900 images would get downloaded at the last download path of the user which is also not good

**Comment by DEC1MU5** [comment]
I am pleased to report that at some point the archive appeared in the download folder, so your app does work, just slowly with lots of images, perhaps a dialog warning the user would help people like me who got alarmed. It requires patience I guess.

**Comment by HuiiBuh** [comment]
It could be the Cas that you got blocked in the middle of the download.
Do you have some kind or error. txt file in your zip? 

I am planning on adding some information for thr zip process as well

**Comment by HuiiBuh** [comment]
Did any of you have this problem in the last month?
Otherwise i will close this issue...

**Comment by DEC1MU5** [comment]
> Did any of you have this problem in the last month?
> Otherwise i will close this issue...

I think you can close it, but I just think the process took too long without any prompts alerting the user what was going on.

**Comment by HuiiBuh** [comment]
Perfect
