### ISSUE TITLE
Filenames are concatenated

### ISSUE THREAD

**Issue by xioren** [HuiiBuh/InstagramDownloader#121]
**Describe the bug**
Filenames are concatenated to "username_15344832522622289723402428593461544981287242n". i.e. missing the underscores "_".

**To Reproduce**
1. Go to stories
2. Download any image or video

**Expected behaviour**
Filenames should be in the format "username_153448325_2262228972340242_8593461544981287242_n"

**Screenshots**

**Desktop (please complete the following information):**
 - firefox
 - Version 4.0.0

**Additional context**

**Comment by HuiiBuh** [comment]
The filename is correct.
The format should be `username_imageid`.

In your example `username_15344832522622289723402428593461544981287242n` is correct. The `n` is a part of the image id.

**Comment by HuiiBuh** [comment]
Is there a reason you want the format to be different?

**Comment by xioren** [comment]
Because that's how Instagram formats them. Each part separated by an underscore mean something different.

**Comment by HuiiBuh** [comment]
You are right. But as I said. I don't se an advantage. This just confuses the end user.
If you tell me the use case I will concider it and perhaps not remove the underscore.
