### ISSUE TITLE
Where do the pictures go?

### ISSUE THREAD

**Issue by waximik561** [HuiiBuh/InstagramDownloader#122]
I clicked "Download All" but I don't see the pictures anywhere, or a zip file. I checked in Downloads and Pictures and did a search of my whole drive. It doesn't say in the Firefox extension where they go, or in the instructions. Thank you.

**Comment by HuiiBuh** [comment]
I don't know.
Where do normal files get saved if you download them?
That is exactly the place where they get saved to

**Comment by waximik561** [comment]
They would normally go to the Download folder, but I searched my entire drive and there are no new photos and no new zip files after I run "Download All"

**Comment by HuiiBuh** [comment]
Strange. Perhaps you tried to download to many images

**Comment by waximik561** [comment]
It was 426, it didn't say there was a limit and it said if you went over 1,000 Instagram might temporarily ban you, suggesting 1,000 was a reasonable number. I also tried stopping at 100 just to see whether that might be it

**Comment by waximik561** [comment]
⭐ I think i figured it out, if you download pictures of one person, you have to clear your entire cache, cookies, etc. before you can download another person. I can't believe no one has ever asked about this issue before. You have to see the blue "downloading and compressing" box in the top left to know it's working, if that box isn't there, there will be no pictures. Thanks very much for your help.

**Comment by HuiiBuh** [comment]
Your solution might trick instagram into thinking that you are a different person. 
I will improve the blue button to show the compression process, perhaps this helps

**Comment by HuiiBuh** [comment]
I am closing this in favour for #120
