### ISSUE TITLE
High res insta display pic

### ISSUE THREAD

**Issue by DealsBeam** [HuiiBuh/InstagramDownloader#123]
The extension downloads a very low res version of the display picture

There are several apps which allow you to download a very high res of a users DP such as Barinsta https://github.com/austinhuang0131/barinsta and high resolution downloader https://github.com/ehmorris/High-Resolution-Downloader-For-Instagram it would be nice to have this for InstagramDownloader as well

Please and thank you

**Comment by HuiiBuh** [comment]
Do you refer to every picture, or just the story,...

**Comment by DealsBeam** [comment]
I'm referring to the user display picture for example: https://prnt.sc/wc9o7k

**Comment by Palina94** [comment]
I can confirm that image-stories are not downloaded in original quality (only 640x1138). Please fix this flaw :)

**Comment by HuiiBuh** [comment]
I just had a quick look and you are right concerning the stories. 
But apart from that this extension does not download higher resolution images than mine. Unfortunately that means that the account image is only 150x150

**Comment by HuiiBuh** [comment]
There seams to be a way around which would allow me to download the full res account image, but it involves reverse engineering Instagram for a bit and I am not comfortable with such a solution. 
SO the highest resolution for account images will be 320x320
