### ISSUE TITLE
Creating batch downloads in groups for staggered downloading

### ISSUE THREAD

**Issue by Allen-Kwan** [HuiiBuh/InstagramDownloader#124]
As the extension notes, you can get blocked if you try to download grab too many links at once - would it be possible to save the links that the extension is catching as it scrolls through a profile for downloading later?  That way you can download in batches and potentially avoid the IP ban.

Edit:  or would an even slower download speed possibly help against the rate limiting/ban issue?

**Comment by HuiiBuh** [comment]
Hey the idea is great, but I think this takes to much time to implement. 
If you want to create a PR, and implement it you can do it, but apart from that I think this is to much work. 
I will however make the changes requested in #110 which will help you
