### ISSUE TITLE
Underscores

### ISSUE THREAD

**Issue by Palina94** [HuiiBuh/InstagramDownloader#125]
Very very small issue, but when naming downloaded files, underscores get lost from the original filename.

For example:

jr_1303688907143561292008913786700417140477432n.jpg

jr_130368890_714356129200891_3786700417140477432_n.jpg

**Comment by HuiiBuh** [comment]
I remove them for readability. Is there a reason you want them to stay?

**Comment by Palina94** [comment]
Just for organization. I would prefer them...

**Comment by HuiiBuh** [comment]
OK. I will leave them in the next release

**Comment by HuiiBuh** [comment]
I will close it when the feature is implemented. Otherwise I will forget it ;)

**Comment by Palina94** [comment]
Haha OK 👍
