### ISSUE TITLE
Download button not working on posts but works on stories and profile pictures (possible rate limiting?)

### ISSUE THREAD

**Issue by firehawk12** [HuiiBuh/InstagramDownloader#126]
**Describe the bug**
The download button on posts and the "Download All" button don't work any more, however I can still download stories and profile pictures.

I believe this may be due to rate limiting or some kind of ban on my account, because a) the issue persists on different browsers (Chrome and Firefox) and on different computers so it doesn't seem to be a browser-based issue and b) the download button on posts works when I switch to another account.

But I'm not sure if it would be possible to know if it's an issue with my account?  Does the extension throw any kind of error if it's unable to retrieve a download link for a post?  Or would there be any way to check if the extension is trying to download an image and failing?

**Comment by Tombo15** [comment]
Had the same issue yesterday. The problem apeard after downloding many posts. I waited untli the next day and it all worked again.
Looks like an limitation issue of IG.

**Comment by HuiiBuh** [comment]
Looks like rate limiting to me. 
I am closing this, because I sadly cannot help
