### ISSUE TITLE
Problems with bulk download

### ISSUE THREAD

**Issue by Apothman777** [HuiiBuh/InstagramDownloader#127]
Same bug ast the other person describes - does not download images onto hard-drive after "Downloading cycle) - no blue box on the upper left side of screen showing downloading and creating the .zip file. Tried clearing cache multiple times as thats a pain as I have to re-sign into Instagram. Have had to uninstall and reinstall Instagram Downloader, etc. Works sporadically! Annoying. Problems with bulk download

**Comment by HuiiBuh** [comment]
I am closing this in favour for #120
