### ISSUE TITLE
wont compress after hitting download all

### ISSUE THREAD

**Issue by ericamtx** [HuiiBuh/InstagramDownloader#132]
**Describe the bug**
Download all, gathers all pic info, --> media collection complete download will proceed in background. Doesn't continue beyond that.
**To Reproduce**. 
1. Go to download all. CLick,  
2. wait for it to start collecting ( sometimes it freezes here and you click stop download)
3. then it collects, says media collection is complete. Hit close, nothing happens.

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - Resolution: [2K] 1366 x 768
 - Browser [e.g. chrome, safari] chrome

**Smartphone (please complete the following information):**
 - Resolution: [2K]

**Additional context**

initially, it worked flawless, now i cant bulk save or even single save, nothing comes up when i click on any pics to save. not even an  error.

**Comment by HuiiBuh** [comment]
Sounds like you where banned?

**Comment by HuiiBuh** [comment]
Sounds like you where banned?

**Comment by ericamtx** [comment]
works again, what was the likely thing i did to cause this. so i can avoid again

**Comment by HuiiBuh** [comment]
I think you tried to download to many images with the bulk download.
