### ISSUE TITLE
Error when linking/embedding images to Adobe Illustrator

### ISSUE THREAD

**Issue by lurvey** [HuiiBuh/InstagramDownloader#133]
**Describe the bug**
Error "Illustrator could not read file" when linking/embedding images to Adobe Illustrator

**To Reproduce**
1. In Adobe Illustrator
2. File...
3. Place...
4. Select an image produced by InstagramDownloader

**Expected behaviour**
Image should be placed into Illustrator

**Screenshots**
<img width="606" alt="Screen Shot 2021-01-13 at 10 37 57 AM" src="https://user-images.githubusercontent.com/10643475/104494530-6ea42b80-558b-11eb-999e-993359dfcd72.png">

**Additional context**
Same result whether the image in Linked or Embedded. Linking the same file in InDesign seems to work fine, same with opening it in Photoshop. A workaround is to resave the image as a different file type in Photoshop, but it would be really nice to avoid this extra step. Otherwise, this plugin has been super useful for me. Esp. love that the IG handle is automatically in the file name, other Extensions don't have this feature. Thanks!!

**Comment by HuiiBuh** [comment]
I don't know if I can help you with this. I only download the image from Instagram and do not any post processing with it.
Saving the image with another file extension would be a possible workaround, but I don't to change the file type because I want to preserve the original.

**Comment by lurvey** [comment]
Thanks for the message back! I didn't mean to be so formal with my request
haha, just wondered if you knew anything about it. Will try that!
