### ISSUE TITLE
Download button sometimes is not immediately available

### ISSUE THREAD

**Issue by auanasgheps** [HuiiBuh/InstagramDownloader#134]
**Describe the bug**
Hello, I've noticed that the download button sometimes is not available. It appears if I close and re-open the post.
It happens only on multi-photo post and is not always consistent, because sometimes it just works on the first click.

**To Reproduce**
1. Open a post with multiple photos
2. Notice the download button is missing
3. Close and reopen
4. Download button is available

**Expected behaviour**
Download button should be available immediately like on single posts.

**Screenshots**
I can record a screencapture if you really need it

**Desktop (please complete the following information):**
 - Resolution: 1080p
 - Browser Chrome v87 64-bit

**Comment by HuiiBuh** [comment]
Thanks for the report.
I can reproduce your issue and will fix it soon

**Comment by auanasgheps** [comment]
Super extra fast fix! Thanks sir.
