### ISSUE TITLE
Ability to download while using 'Layoutify: Improved Layout for Instagram'

### ISSUE THREAD

**Issue by ghostresonance** [HuiiBuh/InstagramDownloader#135]
Can you add the ability to download images while using 'Layoutify: Improved Layout for Instagram'? This extension optimizes how desktop browser IG looks and it would be wonderful if while using it we can download images. The download button does not show up for images while using both extensions.

**Comment by HuiiBuh** [comment]
Hi, thanks for the issue. I a afraid I will not support this feature, because it is enough work to keep up with the changes Instagram is making. 
I don't have the time to rewrite some logic, because the creator of another extension has updated their code.
