### ISSUE TITLE
Doesn't download photo stories

### ISSUE THREAD

**Issue by iWajdi** [HuiiBuh/InstagramDownloader#137]
**Expected behaviour**
The download button does download video stories but when it's a photo it doesn't download it

**Device (please complete the following information):**
- Resolution: 1366x768
- Browser: Chromium based browsers 
- Extension Version: 4.2.1

**Comment by HuiiBuh** [comment]
OK I will have a look

**Comment by steelowheel** [comment]
Firefox 86.0 here, I can download photos from Stories, but some photos are cropped to 1:1 size and only catch the middle of image.

**Comment by HuiiBuh** [comment]
Hey. 
I tried to reproduce your issue, but did not manage it. 
Could you send me the link to a story where this happens?

**Comment by HuiiBuh** [comment]
Do you still have the issue, or can I close the issue?

**Comment by iWajdi** [comment]
Yes, I still have the problem. I just retested it, and still the same. I don't know if it's an extension problem or a browser problem since I use the latest version EDGE Chromium.

**Comment by HuiiBuh** [comment]
Are any errors in the clonsole?

**Comment by iWajdi** [comment]
Yes, I just noticed, although I never used the console like this before: 
![image](https://user-images.githubusercontent.com/77938896/116783826-de7de980-aa88-11eb-966a-ef8f3ae4c498.png)

**Comment by HuiiBuh** [comment]
Wonderful. I just fixed this error in #166, so in version 4.4.0 this issue should be fixed
