### ISSUE TITLE
Bulk download 10 Photos post

### ISSUE THREAD

**Issue by iWajdi** [HuiiBuh/InstagramDownloader#138]
It would be nice if this extension be able to download a 10 Photo post together instead of each separately.

**Comment by HuiiBuh** [comment]
Press Strg +s, or ctrl + s to save the post

**Comment by iWajdi** [comment]
> Press Strg +s, or ctrl + s to save the post

Well that downloaded the photo of a post for example this one " https://www.instagram.com/p/CKWuJWVFvgV/ " but it didn't download the photos in her stories

**Comment by iWajdi** [comment]
Yep that worked, but it would be nice if those photos had the username of the account

**Comment by HuiiBuh** [comment]
I am. afraid I cannot download every story the way I download the post

**Comment by iWajdi** [comment]
Aha. I get it, I hope you figure it out in the future, it would be really helpful to be implemented but thank you for the effort 🥰🥰

**Comment by HuiiBuh** [comment]
I get that but it would be to much work and reverse engineering, so I am afraid this feature is unlikely to ever come
