### ISSUE TITLE
Download All - function, no names in title, only numbers

### ISSUE THREAD

**Issue by Dimich91** [HuiiBuh/InstagramDownloader#139]
Dear developer team,
the download with Download All feature is way easier for many saved pictures. Unfortunately the filename is replaced by a number instead of the name how it was used to be on a single download. 
This makes it almost not possible to sort the pictures and videos. 
Can the same name-giving procedure (or better) be transfered to the Download All feature?
Kind regards

**Comment by rhodessteve** [comment]
This would be a great enhancement. Some sort of timestamp in the filename too.

**Comment by HuiiBuh** [comment]
I am going to. impelemnt you request, it will just take a bit of time, because I am currentely very busy

**Comment by dtastic** [comment]
This would be useful when you have time to work on it. Thank you.

**Comment by HuiiBuh** [comment]
I will close this as a duplicate.
Your issue will be tracked at #110
