### ISSUE TITLE
Add ability to download Reels

### ISSUE THREAD

**Issue by MoosMas** [HuiiBuh/InstagramDownloader#140]
**Is your feature request related to a problem? Please describe.**
The extension can't download Reels. This would be a real nice feature to have.

**Comment by HuiiBuh** [comment]
Hey, how do I even see a reel on a desktop computer?
Could you perhaps send me a link to an ig reel, otherwise I don't know how to implement your feature

**Comment by MoosMas** [comment]
You can see a users reels by clicking on reels on their profile. See the sceenshot below.


![image](https://user-images.githubusercontent.com/20402877/106742610-89fbd700-661d-11eb-93bf-bc6b17a94c95.png)

**Comment by HuiiBuh** [comment]
Thanks. I have not noticed that.

**Comment by kryztoval** [comment]
I just stumbled upon this as well. Odd that it doesn't show up on reels.
