### ISSUE TITLE
Support Paypal

### ISSUE THREAD

**Issue by szopppppen** [HuiiBuh/InstagramDownloader#141]
Hi, 
i'm using your addon and i think its great. I wanted to donate using paypal but I get information that you dont accept private transfers

**Comment by HuiiBuh** [comment]
Thanks for this issue. I am already trying to get this issue resolved. Somehow my PayPal got flagged.
I hope this will be resolved in the next week,but I will keep you updated.

And thanks for your support

**Comment by HuiiBuh** [comment]
Hey, 
I am happy to announce that I finally resolved the issue with PayPal. 
It is now possible to send me money again ;)
