### ISSUE TITLE
Can't download stories made for close friends

### ISSUE THREAD

**Issue by auanasgheps** [HuiiBuh/InstagramDownloader#143]
**To Reproduce**
Steps to reproduce the behaviour:
1. Find a story made for close friends (green ring)
2. Open it and try to download
3. Nothing happens

**Expected behaviour**
Story should be downloaded

**Device (please complete the following information):**
- Resolution: 1440p
- Browser: Chrome 88
- Extension Version: 4.2.1

**Additional context**
I was able to replicate this issue with different friends multiple times.

**Comment by HuiiBuh** [comment]
I unfortunately don't use Instagram and therefore don't have any close friends ;)

Could you send me the result of the following queries?. 
I think this should help me.

```javascript
// Image
document.querySelector(".y-yJ5")

// Close button
document.querySelector(".K_10X").innerHTML

// Get the content of the most of the page
document.querySelector(".Igw0E").innerHTML
```

And perhaps an image would be nice. I have never seen a story for close friends

**Comment by auanasgheps** [comment]
Made another test and today worked fine. I don't get _that many_ close friends stories, so I'll close the issue for now.

How can I get the result of those queries? Can't find much in the browser console.

**Comment by HuiiBuh** [comment]
Press f12
and just copy paste the queries and tell me the result

**Comment by auanasgheps** [comment]
F12, then what tab?

**Comment by HuiiBuh** [comment]
the console.
Perhaps pasting code is blocked, because of security reasons. In this case you have to follow the instructions which appear in the console

**Comment by auanasgheps** [comment]
Closing, will reopen when the issue rises again with the requested info.
