### ISSUE TITLE
Add support for downloading posts which have multiple images

### ISSUE THREAD

**Issue by desbest** [HuiiBuh/InstagramDownloader#144]
If an post or thread on instagram has multiple images, the download button only downloads one image, when there's more than one. This behaviour also happens when using the "download all" feature to download everything from a person's profile.

Please make it so it can download all the images associated with a post or thread, if there are multiple images.

**Comment by HuiiBuh** [comment]
Press 
Strg + s or
Control + s

**Comment by desbest** [comment]
Can you make the Control + S feature on a multiple image post, visible in the interface for a user to click on?

Also the "download all" feature that downloads all of a user's images, when it encounters a post that contains multiple images, it only downloads one image, not the entire gallery. So can you update it so it downloads the additional images on the post?

**Comment by HuiiBuh** [comment]
I will remove the download all button in the post.

**Comment by HuiiBuh** [comment]
And I will think about adding a save-all button, but this is not very hight on my priority list

**Comment by desbest** [comment]
I've just checked now by using the extension again, and I see that the "download all" button DOES download every image from threads which contain multiple images.
It wasn't like that months ago, but it works now. So it looks like that specific feature is already implemented right now.
Sorry for the confusion. It seems like I was talking about a previous version.

Well it's just the download image on a any given thread that would need changing, but you said you'll do it later but it's low priority. I can live with Ctrl + S for that for now.
