### ISSUE TITLE
compression step has become very slow

### ISSUE THREAD

**Issue by thursmo** [HuiiBuh/InstagramDownloader#145]
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to URL 'https://www.instagram.com/world_record_egg/'
2. Click on "Download All"
3. Stop collection after a reasonable count (e.g. 50)
4. Wait. The first few steps are completed within seconds, but the "Compression progress" stage will take several minutes, even for a small number of files.

**Expected behaviour**
The compression stage should only take a few seconds. It used to be much faster. 

**Screenshots**

**Device (please complete the following information):**
- Resolution: 1920x1080
- Browser: Chrome 89.0.4389.48 (running on ChromeOS)
- Extension Version: 4.2.1

**Additional context**
I noticed the change in performance on February 16, 2021.

**Comment by HuiiBuh** [comment]
I think there is nothing I can make to change that. 
The last changes I made where mid January. Perhaps you don't have enough ram and your device has to swap to be able to complete the compression. 

I think this an issue on you end and not an issue with the downloader

**Comment by thursmo** [comment]
It continues to work as expected on MacOS running Chrome 88.0.4324.182 and it was working as expected under Chrome OS with Chrome 89.0.4389.16. It's possible that something changed between chrome versions.

**Comment by HuiiBuh** [comment]
Perhaps. I really don't know. But my extension has not changed, so i would suspect so
