### ISSUE TITLE
Cannot download stories with localization parameter in URL

### ISSUE THREAD

**Issue by Noobsai** [HuiiBuh/InstagramDownloader#146]
Hello!
Sometime Instagram or search engine add localization parameter in page URL, for example: ?hl=en.

For the page https://www.instagram.com/world_record_egg/?hl=en the story URL will be https://www.instagram.com/stories/world_record_egg/2513980750976294992/?hl=en

Extension is using location.href
https://github.com/HuiiBuh/InstagramDownloader/blob/f0b32166b435aed9f4330e0a2a4915ab9b049951/src/ts/downloaders/StoryDownloader.ts#L30

what generates a wrong request URL https://www.instagram.com/stories/world_record_egg/2513980750976294992/?hl=en?__a=1
with the error: `VM199:1 Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0` (response is not JSON)
Story doesn't downloaded.

- Extension Version 4.2.1

Thanks!

**Comment by HuiiBuh** [comment]
Perfect. 
Thanks for the report and your investigation.
