### ISSUE TITLE
I can download photos from Stories, but some photos are cropped to 1:1 ratio

### ISSUE THREAD

**Issue by steelowheel** [HuiiBuh/InstagramDownloader#147]
Firefox 86.0 here, I can download photos from Stories, but some photos are cropped to 1:1 ratio and only catch the middle of image.

_Originally posted by @steelowheel in https://github.com/HuiiBuh/InstagramDownloader/issues/137#issuecomment-787443576_

**Comment by HuiiBuh** [comment]
Does this issue still exist, or can I close it?

**Comment by steelowheel** [comment]
> 
> 
> Does this issue still exist, or can I close it?

I haven't used the addon for a while so I don't know. So yeah you can close it.
