### ISSUE TITLE
Speed?

### ISSUE THREAD

**Issue by Decme** [HuiiBuh/InstagramDownloader#148]
During download we have the option of selecting speed 1 to 9
I selected speed 2 and it seemed to go incredibly fast. My concern is being banned or tempbanned for downloading too quickly. Is speed 1 fastest or slowest?

**Comment by HuiiBuh** [comment]
I think 9 is the fastest.
I will make some changes which make 1 even slower

**Comment by HuiiBuh** [comment]
Implemented more clear labeling in the new version
