### ISSUE TITLE
photos dont download even after collecting all photos. Once we press download all, it starts collecting photos, but nothing downloads in download folder.

### ISSUE THREAD

**Issue by rajesh1026** [HuiiBuh/InstagramDownloader#149]
# Important: Issues without the following information will be closed

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to URL 'https://www.instagram.com/gyansandhya/'
2. Click on 'download all'
3. Select the download speed
4. Press continue
5. press " stop download"
6. Press "close"

3. See error

**Expected behaviour**
it should start compressing all photos selected and automatically download in " download" folder

**Screenshots**
files attached.

**Device (please complete the following information):**
- Resolution: [e.g 2K]
- Browser [e.g. chrome, Microsoft Edge]
- Extension Version [e.g. 4.0.1]

**Additional context**
it should download all selected photos in zipped version, but it is not doing it. please suggest what went wrong?
[Insta issues.docx](https://github.com/HuiiBuh/InstagramDownloader/files/6151571/Insta.issues.docx)

**Comment by HuiiBuh** [comment]
please provide the required details or I will close the issue

**Comment by rajesh1026** [comment]
Hello, I am trying to download photo from instagram, in right side i see, download all button, when i press, it selects many photos and then i stop collecting images and starts download
once Media collection is complete and i press close button, nothing is in Download folder

earlier it was showing compressed zip files, but now its stopped. pls advise why its not workign now

**Comment by HuiiBuh** [comment]
I have an issue template. 
This template states the information I need.

If you dont provide this information I will close the issue

**Comment by rajesh1026** [comment]
pls send template at raj.1026@outllook.com

**Comment by HuiiBuh** [comment]
You issue comment includes the unfilled template.

**Comment by rajesh1026** [comment]
updated in above

**Comment by HuiiBuh** [comment]
you still did not provide the browser, os, and addon version

**Comment by HuiiBuh** [comment]
and resolution

**Comment by rajesh1026** [comment]
Resolution:  i dont know.. I am using a good quality ryzen 5 computer
Browser [e.g. chrome, Microsoft Edge]
Extension Version [4.2.1)

**Comment by rajesh1026** [comment]
OS= Windows 365

**Comment by rajesh1026** [comment]
no reply?

**Comment by HuiiBuh** [comment]
No "no reply".
This is not my job and I am doing this in my free time. So please show a bit of appreciation and dont try to pressure me into replying. 
Regardless. I will take a look at your issue

**Comment by i007x** [comment]
The 4.2.2 version 'download all 'has been able to work normally, thanks for the fix ❤❤ love u

**Comment by HuiiBuh** [comment]
@i007x Thanks for the feedback

**Comment by rajesh1026** [comment]
i downloaded version 4.2.2.. its not downloading even a single image. pls help
