### ISSUE TITLE
Speed Bug

### ISSUE THREAD

**Issue by Null36** [HuiiBuh/InstagramDownloader#154]
Not sure of this is a bug or whether you have developed it this way but I have noticed that if I set the speed below 5 the script does not download all the pictures and videos from the users account, I am using the latest version and It it installed as an extension on the latest version of chrome.

**Comment by HuiiBuh** [comment]
I will close your issue in favor of #148. 
I will take a look at it and hopefully fix the bug soon. I think the scroll speed is to fast. Perhaps make it slower so the extension has the time to collect the images
