### ISSUE TITLE
Support new post modal view

### ISSUE THREAD

**Issue by andrewsuzuki** [HuiiBuh/InstagramDownloader#157]
It seems they recently added a new modal view. When you click an image, it now displays that image in a modal by default. It seems the ctrl+s hotkey works for it, but I don't see any download icon.

**Comment by HuiiBuh** [comment]
The download icon should be next to the bookmark icon.
If it is not there then there is a problem with my extension

**Comment by andrewsuzuki** [comment]
The new post modal only appeared in the last week. Screenshot:

![instagram-post-modal-2021-04-04](https://user-images.githubusercontent.com/947837/113516930-0857f500-954b-11eb-8d05-5a8eb9159669.png)

It opens when you click a photo on a profile page.

**Comment by HuiiBuh** [comment]
You seem to have a newer versiom of Ig than i have.
I am afraid this has to wait until i get the update too, or xou xould creatr a PR and fic thr issue. I think all you had to do to fix the issue temporarily is changr thr querySelectors
