### ISSUE TITLE
Can't download all pictures

### ISSUE THREAD

**Issue by jedikalimero** [HuiiBuh/InstagramDownloader#158]
When I click the "Download all" button, only 29 pictures are downloaded. but the account has 58 pictures. It happens to me in all accounts even if I scroll down to the very first publication before pressing the "Download all" button.

**Comment by HuiiBuh** [comment]
Have you tried reloading befor xou start the download?
Perhaps thid will help

**Comment by HuiiBuh** [comment]
Or try to set thr download speed to 9

**Comment by jedikalimero** [comment]
Yes, reloaded the page several times. No difference.
Speed 9 is faster or slower? It is not clear since it is not explained anywhere, I think.

**Comment by HuiiBuh** [comment]
9 is the slowest.
You are right. I should explain it somewhere
