### ISSUE TITLE
Download Icon disappeared

### ISSUE THREAD

**Issue by f0rr357** [HuiiBuh/InstagramDownloader#160]
instagram changed layout for single and multiple image posts. Just noticed on incognito mode layout doesn't change, intersting.
![Screenshot_2021-04-08 Instagram ( instagram) • Foto e video di Instagram](https://user-images.githubusercontent.com/54697277/114011877-02715500-9866-11eb-9895-a79b0d1c2368.png)
![Screenshot_2021-04-08 Instagram ( instagram) • Foto e video di Instagram(1)](https://user-images.githubusercontent.com/54697277/114011905-08673600-9866-11eb-99cb-597f0bf9b7f7.png)

**Comment by HuiiBuh** [comment]
Got fixed by #159

**Comment by f0rr357** [comment]
i have to update my extension?
