### ISSUE TITLE
Niclas.xml & niclas.xml on a case-insensitive file system giving git headaches

### ISSUE THREAD

**Issue by marchage** [HuiiBuh/InstagramDownloader#161]
**Is your feature request related to a problem? Please describe.**
I was writing a bug report, but it's more a feature request I would say so I will past my original text here:

# Hi, 

Maybe I should post this at git or spend more time searching for ways to deal with this when it happens. But does it really need those 2 files, one of which is written with a capital "N"?

## Important: Issues without the following information will be closed

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to URL 'https://github.com/HuiiBuh/InstagramDownloader/'
2. git clone
3. git status

**Expected behaviour**
nothing

**Screenshots**

**Device (please complete the following information):**
- whatever browser, unrelated.
- Be on a system that has a case insensitive filesystem, like some/any/many? Macs.

**Additional context**
Concerns the following paths:

  '.idea/dictionaries/Niclas.xml'
  '.idea/dictionaries/niclas.xml'

**Side note/Unrelated**
As a side note, something which I am piggy-bagging in here but is unrelated: **Nice setup! I loved it.** I dissected it a bit, learned a bit of typescript, enjoyed the watch feature, I tried it out but got 429 responses after 1 go (which did finish, it worked perfectly!), repurposed it to something else, came back and made the background bulk downloader synchronous i.s.o. async, and - of course it is much slower but - did not get 429's anymore. I didn't test limits (intentionally), but are you sure it should only sleep when scrolling down and not during actual downloading? And is downloading not something that would should be done one-by-one? Much more reliable (imo) for that other thing I repurposed it for. I guess you should keep it as it is to avoid too many new bug reports about "slow download speeds" etc, but from another perspective you could say you are increasingly likely to get 429's this way. Anyway, best of luck/regards.

**Comment by HuiiBuh** [comment]
Hey. These files get auto generated by Intellij. So i don't intend ro delete them.

The bulk download is intentionally async to improve the download speed. Perhaps it would be better to create a global http client which applies some kind of rate limiting and retries to avoid these 429 errors.

**Comment by HuiiBuh** [comment]
Edit
I did not understand thr problem you were describing with the files.
I will delete one of these files to the windows users the ability to clone thr extension without a problem

**Comment by marchage** [comment]
Oh okay, don't bother, Windows shouldn't have that issue. The important part is in bold :)

**Comment by HuiiBuh** [comment]
Haha thanks :)
Glad you liked my setup
