### ISSUE TITLE
Can't download anything

### ISSUE THREAD

**Issue by wzx1000** [HuiiBuh/InstagramDownloader#163]
I was using InstagramDownloader yesterday and suddenly i can't download anything. I use Chrome and tried to reload page, quitting chrome, starting again and nothing happens. Could be an extension bug or something? pls help

**Comment by HuiiBuh** [comment]
See #162

**Comment by wzx1000** [comment]
#

> See #162

![Screen Shot 2021-04-15 at 12 42 26 PM](https://user-images.githubusercontent.com/82600242/114914873-7bcdf200-9de8-11eb-9b13-5f6added806e.png)

It's the same with the #162 ? appears this to me

**Comment by HuiiBuh** [comment]
Yes that is rhe reason I closed it.
But thanks for the screenshots
