### ISSUE TITLE
Unable to download the second file of the story

### ISSUE THREAD

**Issue by hyunbb628** [HuiiBuh/InstagramDownloader#166]
Extension Version [e.g. 4.3.0]
Browser edge Version 90.0.818.46
The first file of the story can be downloaded, but the button of the second file can't be downloaded normally. There is no response when you click download.

https://user-images.githubusercontent.com/83266745/116191787-7e710580-a75f-11eb-8072-a33fb8b5d2d3.mp4

**Comment by HuiiBuh** [comment]
Do you have an example link for me?
It works for me at the moment. Is there any error in the browser console or in the background script of the extension?

**Comment by hyunbb628** [comment]
> Do you have an example link for me?
> It works for me at the moment. Is there any error in the browser console or in the background script of the extension?

跨源读取阻止(CORB)功能阻止了 MIME 类型为 application/json 的跨源响应https://graph.instagram.com/logging_client_events。有关详细信息，请参阅 https://www.chromestatus.com/feature/5629709824032768。
e.sendWithBeacon @ 055cc1b3b394.js:91
sendWithBeacon @ 055cc1b3b394.js:104
s @ 055cc1b3b394.js:103
(匿名) @ 055cc1b3b394.js:103
e.applyWithGuard @ 127b71bf8b94.js:14
n.__emitToSubscription @ 127b71bf8b94.js:22
n.emit @ 127b71bf8b94.js:22
o.emit @ 127b71bf8b94.js:21
n.emit @ 127b71bf8b94.js:27
emit @ 127b71bf8b94.js:20
(匿名) @ 127b71bf8b94.js:19
3extension.js:1 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined
    at extension.js:1
    at Array.forEach (<anonymous>)
    at extension.js:1
    at HTMLSpanElement.<anonymous> (extension.js:1)
    at Generator.next (<anonymous>)
    at i (extension.js:1)

Is it these? I don't quite understand，I tried again, all the pictures in the story can't be downloaded, only the video can be downloaded。

**Comment by hyunbb628** [comment]
> Do you have an example link for me?
> It works for me at the moment. Is there any error in the browser console or in the background script of the extension?

download-functions.ts:88 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined
    at download-functions.ts:88
    at Array.forEach (<anonymous>)
    at extractSrcSet (download-functions.ts:85)
    at HTMLSpanElement.<anonymous> (StoryDownloader.ts:42)
    at Generator.next (<anonymous>)
    at fulfilled (tslib.es6.js:71)

Is it these? I don't quite understand，I tried again, all the pictures in the story can't be downloaded, only the video can be downloaded。

**Comment by hyunbb628** [comment]
![QQ截图20210429133434](https://user-images.githubusercontent.com/83266745/116506345-a68f6e80-a8ef-11eb-8875-b4b3e98b4af6.jpg)

**Comment by HuiiBuh** [comment]
thanks this helps a lot
