### ISSUE TITLE
Every photo and video download fails

### ISSUE THREAD

**Issue by DarthSaber** [HuiiBuh/InstagramDownloader#168]
This issue began today. The Mozilla screenshots that I was taking of my friends' activities downloaded fine, but every photo and video that I tried to download with "Instagram Downloader" failed, both in their stories and on their page. 

I tried returning to older versions but the problems persisted. Other "Instagram downloaders" extensions for Firefox work after their fashion but none can compare to this Instagram Downloader extension.

**Comment by AJDulk** [comment]
I can confirm that this is a universal problem - I have 2 computers and both have the same problem. It is possible to download manually by right clicking the failed download and selecting "Copy link" and then manually pasting that in the address bar to get the picture or video and then right clicking that to download - so Firefox still has the ability to download the files, proving that there is something blocking in the method the add on uses to download.

**Comment by NicotherZ** [comment]
> 
> 
> I can confirm that this is a universal problem - I have 2 computers and both have the same problem. It is possible to download manually by right clicking the failed download and selecting "Copy link" and then manually pasting that in the address bar to get the picture or video and then right clicking that to download - so Firefox still has the ability to download the files, proving that there is something blocking in the method the add on uses to download.

With this method can't get image/video max quality

**Comment by stvoidit** [comment]
it works through a script in bookmarks.
`javascript:(() => {
	if (this.__additionalData[location.pathname].data.graphql.shortcode_media.edge_sidecar_to_children) {
	  this.__additionalData[location.pathname].data.graphql.shortcode_media.edge_sidecar_to_children.edges.forEach(e => {
	  if (e.node.is_video) {
		window.open(e.node.video_url, "_blank");
	  } else {
		  let dispRes = e.node.display_resources;
		  let src = dispRes[dispRes.length-1].src;
		  window.open(src, "_blank");
	  }
	});
	}
	if (this.__additionalData[location.pathname].data.graphql.shortcode_media.is_video) { 
		window.open(this.__additionalData[location.pathname].data.graphql.shortcode_media.video_url, "_blank");
	}}
)();`

**Comment by HuiiBuh** [comment]
this could be related to #165
I will update today which will hopefully fix the problem

**Comment by HuiiBuh** [comment]
Just updated it.
Could you check if Version 4.3.1 works for you?

**Comment by NicotherZ** [comment]
Download works but post and image stories are not downloaded max quality

**Comment by HuiiBuh** [comment]
I think it is. At least I don't know how to get a higher resolution with the api instagram provides

**Comment by LeFH18** [comment]
Hi, I have the same problem. The thing is, when I try to download a bunch of posts (150 or so), the extension says they are being compiled, however nothing happens afterwards. Yesterday I tried and it only downloaded a .zip with an error message. I've tried in both Chrome and Firefox but neither works.

**Comment by Petermhen** [comment]
Working for me now. Thanks!

**Comment by HuiiBuh** [comment]
the bulk download problem will be tracked at #170
