### ISSUE TITLE
A super slow download option to get around 200 post download temp ban.

### ISSUE THREAD

**Issue by wishusknight** [HuiiBuh/InstagramDownloader#169]
What I am thinking of, is would it be possible to implement a type of really slow download that can tag posts much slower and say download only a couple of posts a second or even just 1 per second? Or do like 20, then stop for 20 seconds... Or perhaps implement the ability to pic a range of posts to pick when "download all" is selected. Many accounts go well over the 200 post mark so it makes it impossible to get the entire thing bulked down. And also many are disappearing from Imginn (even when it is reliable). 

If a user bumps into the 200 post limit too many times their account gets deleted. And that sucks. lol 

This is such a great add on, and so far is the one that really does do what it promises. I see you are working on a fix for the current instagram change that broke downloads, so I am eagerly awaiting the update!  Keep up the awesome work.

**Comment by HuiiBuh** [comment]
this could be related to #165
I will update today which will hopefully fix the problem

**Comment by HuiiBuh** [comment]
Hi, I just implemented a slower image recovery.
Unfortunately you should still only collect a certain amount of images, because the compression process is only in RAM and I think more than 1000 to 2000 images might break things. I don't know after how many images Instagram will ban you. I think you just have to give it a try ;)

Downloading ranges and picking up at a certain image is not a priority for me, but if you want to implement the feature go ahead.

**Comment by wishusknight** [comment]
The IG threshhold seems to be about 250 items regardless of how slow the addon is set.  To give an idea of what I mean, it needs to have a setting that can restrict to initiating 1 item per second or 1 item per 2 seconds. So something labled like "come back in an hour slow".. lol. 

Currently there is no way to limit how many images it will collect on a large account.  And with 16 gigs of ram on windows and current firefox it can successfully handle a zip archive of about 2 gigs before that process thread in FF barfs on Imginn. Your addon seems to be less ram hungry than their applet. So if the account is mostly pictures that is good for a couple of thousand items. On an account that has a lot of large video files I have had zip's as large as about 4.5 gigs form reasonably well without slamming the computer. That was only about 100 items as well in that particular instance. 

I hope this extra info helps. Thanks again for the time you put in. It really is appreciated.

**Comment by HuiiBuh** [comment]
I will see what I can do. Just don't expect anything in the next time

**Comment by wishusknight** [comment]
Thanks!  Seems like instagram is forever trying to block mass down loaders. They try to keep me from my meme gathering. :(
