### ISSUE TITLE
Bulk downloading now fails, likely as a result of the recent update. 

### ISSUE THREAD

**Issue by DevJake** [HuiiBuh/InstagramDownloader#170]
# Important: Issues without the following information will be closed

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to URL 'https://www.instagram.com/world_record_egg/'. 
2. Click on the 'Download All' button. 
3. Set speed to any value. For example, the default of 5. 
3. The download fails to complete. The page scrolls, images are checked, their data gathered, but the download simply does not occur. This is the same behaviour as seen in Issue #165. 
4. The downloaded zip file simply contains `error_read_me.txt` with some boilerplate of potential solutions. 

**Expected behaviour**
As intended, all images should be downloaded into a zipped file. 

**Screenshots**

**Device (please complete the following information):**
- Resolution: 1920x1080
- Browser Firefox version: 88.0, 64-bit
- Extension Version: [4.3.1](https://github.com/HuiiBuh/InstagramDownloader/releases/tag/v4.3.1)

_There is no issue with disk space availability._ 

**Additional context**
This issue was noted [here](https://github.com/HuiiBuh/InstagramDownloader/issues/168#issuecomment-828831370) by @LefH18. This issue could potentially be a result of the problems and fixes provided regarding Issue #165. 

Downloading individual images is successful. Downloading stories is successful. However, bulk downloads completely fail. **This also includes bulk downloads of single posts with multiple items.**

Immediately upon beginning the bulk download process (gathering images), this error message is presented in the console (complete with its stack trace): 
![Facebook-side API error](https://user-images.githubusercontent.com/4295059/116487327-95ab1280-a887-11eb-9459-373cc44f0c30.png)

I have blurred some information from the screenshot, as I cannot be certain if this is identifiable information. I assume these will not obstruct any bug-hunting process. 

I've tried rebooting Firefox, as well as uninstalling and reinstalling the extension. I've verified I'm definitely using the latest version. I've disabled and removed any other extensions from the browser, with no success. 

Critically, in the _Network_ tab, the same `CORS Request` error is given as in Issue #165. I, therefore, believe these two issues are likely linked.

**Comment by DevJake** [comment]
**A word of warning to other users**, Instagram has just temporarily blocked my account for 'suspicious behaviour', likely from `CORS`-related errors. When selecting to recover my account, the request is rejected and accompanied by more `CORS` errors. I suggest using these features with caution until definitively resolved.

**Comment by HuiiBuh** [comment]
if this is the same problem as #165 it should be a quick fix

**Comment by LeFH18** [comment]
I´m using Chrome and i reinstalled the extension in case it did not updated itself.
**When i try to bulk-download a multi-media post, this error pops up in the console:**
![image](https://user-images.githubusercontent.com/83377298/116614449-f37f3f00-a907-11eb-83b4-cad08354d87c.png)

**And when i try to download a bunch of post from the saved items:**
![image](https://user-images.githubusercontent.com/83377298/116614934-92a43680-a908-11eb-840a-7007a3bd26f3.png)

**Then, when i click "Close" when the extension finished to "compile" the posts:**
![image](https://user-images.githubusercontent.com/83377298/116615142-e4e55780-a908-11eb-86c2-4f87139feda9.png)

**Also, this happens even when i try to download a single-media post, one at a time:**
![image](https://user-images.githubusercontent.com/83377298/116615277-0e9e7e80-a909-11eb-855e-aefb8e33a123.png)
*This did not happened before the update, in which moment i still could download single images. I haven´t tried with stories, profile pics or chat media, so i don´t know if there are more errors.

I hope this information helps to find a solution to this weird bug, and thanks for trying to fix it.

**Comment by HuiiBuh** [comment]
Can you send me the result you see if you visit this url?

https://www.instagram.com/p/CNdPgvghkpJ/?__a=1

**Comment by LeFH18** [comment]
![image](https://user-images.githubusercontent.com/83377298/116652129-8e047000-a952-11eb-9e6d-f088c5c44e3d.png)

It says:

[test1.txt](https://github.com/HuiiBuh/InstagramDownloader/files/6403145/test1.txt)
