### ISSUE TITLE
Unable to download 

### ISSUE THREAD

**Issue by maxgrey910** [HuiiBuh/InstagramDownloader#171]
Since Wednesday i have been unable to download photos while on firefox, I keep getting failed downloads.
Then Today on Chrome I tried to bulk donwload and got an error message and am now unable to donwload anything on Chome as well

**Comment by HuiiBuh** [comment]
extension version?

**Comment by maxgrey910** [comment]
> extension version?

4.3.1
Crome version is Version 90.0.4430.93 (64-bit)  and firefox is Version 88.0 (64-bit)

**Comment by DevJake** [comment]
@maxgrey910 what error message do you receive? It may help the developer if you're able to share any stack traces or network error messages under the dev tools of your browser. I believe the F12 key on both Chrome and Firefox will work (if not, right click and inspect should work). 

I know you said you're on the latest version, but you may need to uninstall then reinstall the extension. I had to do this myself to resolve a similar issue that the latest update fixed.

**Comment by superfreeman1989** [comment]
I reinstalled but it's still not working. Nothing in the console.

**Comment by LeFH18** [comment]
Hi again. I can download single posts again without problems, however the bulk download still does not works.

This time, it downloaded a .zip again with this error text:

[error_read_me.txt](https://github.com/HuiiBuh/InstagramDownloader/files/6410209/error_read_me.txt)

The console shows this:
![image](https://user-images.githubusercontent.com/83377298/116793717-543c8200-aa96-11eb-91e3-2b74a0c627b4.png)
![image](https://user-images.githubusercontent.com/83377298/116793723-64546180-aa96-11eb-81de-6e668e6f74ba.png)

**Comment by DevJake** [comment]
@LeFH18 Issue #170 discusses your specific issue. That issue is now closed, meaning this issue will likely be fixed in the next update.

**Comment by DevJake** [comment]
> 
> 
> @LeFH18 Issue #170 discusses your specific issue. That issue is now closed, meaning this issue will likely be fixed in the next update.

I've just checked and neither the Chrome nor Firefox extension stores have the latest version. I don't know the process of pushing new updates, but I'm sure they will update soon. Hence, you may just need to wait for the new update to roll out :)

**Comment by HuiiBuh** [comment]
@DevJake Thanks for the answers.

I did not want to update so I can test the new automatic update github action and I am pleased to say that it works :)
So both addons should get updated as soon as they pass the review process.

**Comment by inounakade** [comment]
Hey, been unable to download ever since update, no zip file, and before zip file it always come with a error message in the zip.

**Comment by DevJake** [comment]
@inounakade what version of the extension are you using? It just got updated and the latest update fixed my issues with bulk downloading.

If you have any errors in your browser's console or network logs, it'll probably be helpful to the developer to include that information too :)

**Comment by inounakade** [comment]
@DevJake 4.4.3.
![image](https://user-images.githubusercontent.com/10234394/116840740-f3fd2b80-abce-11eb-841a-9ff2580ece06.png)
i got this when i pressed the download button on a image

**Comment by inounakade** [comment]
@DevJake 4.4.3, i got this error when i pressed on any image
![image](https://user-images.githubusercontent.com/10234394/116840852-49d1d380-abcf-11eb-9600-e57419e326f9.png)

**Comment by HuiiBuh** [comment]
@inounakade
Can you send me the result you see if you visit this url?

https://www.instagram.com/p/CNdPgvghkpJ/?__a=1

**Comment by inounakade** [comment]
@HuiiBuh {"message":"","spam":true,"status":"fail"}

**Comment by HuiiBuh** [comment]
looks like ig banned you temporarily.
I am afraid there is nothing I can do

**Comment by inounakade** [comment]
@HuiiBuh yeah rip, thank you anyways tho.

**Comment by superfreeman1989** [comment]
I still cannot download single or bulk posts at all.

**Comment by HuiiBuh** [comment]
Hi i just updated the extension to version 4.4.4.
Do you still have the issues?

**Comment by LeFH18** [comment]
Hi, the extension now works normally and without problems so far for me, thanks for the fix.

**Comment by Kwizatz** [comment]
@HuiiBuh Funny I got the update to 4.4.4 today and now Firefox downloads are not working again.
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://graph.instagram.com/logging_client_events. (Reason: CORS request did not succeed).
```

**Comment by HuiiBuh** [comment]
The graph requests are not from my extension. 
You have to take a look at the background script of the extension

**Comment by inounakade** [comment]
Extension works fine now, thank you for the fix!

**Comment by Kwizatz** [comment]
I am not sure what to look for. clicking the download icon doesn't seem to be triggering a download (I see no network activity), but the downloads list does show the failed download, copying the link and manually entering in the URL field does get the image.

**Comment by Kwizatz** [comment]
Nevermind, fixed on 4.4.5

**Comment by superfreeman1989** [comment]
Download now works! Thanks

**Comment by HuiiBuh** [comment]
Wonderful.
In this case I will close the issue
