### ISSUE TITLE
Download Button Isnt Appearing

### ISSUE THREAD

**Issue by GracieeMC** [HuiiBuh/InstagramDownloader#172]
So after i updated to the latest version the download button has vanished
![image](https://user-images.githubusercontent.com/45043402/116810175-81df0500-ab42-11eb-8f8a-f219ff22bead.png)

**Comment by GracieeMC** [comment]
![image](https://user-images.githubusercontent.com/45043402/116810214-d1bdcc00-ab42-11eb-8a85-cc015a753765.png)
i am on the latest version FYI

**Comment by HuiiBuh** [comment]
which button?

**Comment by HuiiBuh** [comment]
download all is next to the home button

**Comment by GracieeMC** [comment]
![image](https://user-images.githubusercontent.com/45043402/116812724-94603b00-ab50-11eb-91a8-cd71334a6de0.png)
thats the issue its not there

**Comment by GracieeMC** [comment]
So After Reinstalling the addon its fixed
