### ISSUE TITLE
02.05.2021 Update does not work in Chrome

### ISSUE THREAD

**Issue by khaosovidius** [HuiiBuh/InstagramDownloader#173]
Before updating everything was fine.. But after you released the latest update something is wrong. We would be appreciated if you could check the problem. Thank you in advance.

**Comment by ultrasahand** [comment]
same. it's not working

**Comment by HuiiBuh** [comment]
What exactly is not working?
I need a bit more information

**Comment by neelam281181** [comment]
Not able to download anything from Instagram.... till afternoon it was working fine but now it's not working

**Comment by HuiiBuh** [comment]
if you go to the Chrome extension page and take a look at my extension do you see any errors?

**Comment by neelam281181** [comment]
not it's not showing anything....

But when u click on the download mark nothing will happen.... earlier it's
stars downloading the video image etc nut now no action

**Comment by achillar** [comment]
After trying to download any content with the extension I can see the following log in the Google Chrome Console panel:

```
extension.js:1 Uncaught (in promise) Error: Failed to fetch
    at u (extension.js:1)
u @ extension.js:1
Promise.then (async)
l @ extension.js:1
i @ extension.js:1
Promise.then (async)
l @ extension.js:1
(anonymous) @ extension.js:1
t @ extension.js:1
downloadContent @ extension.js:1
7a95c07f03ea.js:81 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://graph.instagram.com/logging_client_events with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.
e.sendWithBeacon @ 7a95c07f03ea.js:81
sendWithBeacon @ 7a95c07f03ea.js:89
c @ 7a95c07f03ea.js:88
(anonymous) @ 7a95c07f03ea.js:88
v @ 6433bf46197a.js:28
```

Using the option to format code, the error line looks like:

```javascript
              , u = ({reject: s, resolve: n},r)=>{
// The line below is throwing the error:
              e.runtime.lastError ? e.runtime.lastError.message === t ? n() : s(e.runtime.lastError) : r && r.__mozWebExtensionPolyfillReject__ ? s(new Error(r.message)) : n(r)
            }
              , h = (e,t,s,...n)=>{
              if (n.length < t.minArgs)
                throw new Error(`Expected at least ${t.minArgs} ${i(t.minArgs)} for ${e}(), got ${n.length}`);
              if (n.length > t.maxArgs)
                throw new Error(`Expected at most ${t.maxArgs} ${i(t.maxArgs)} for ${e}(), got ${n.length}`);
              return new Promise(((e,t)=>{
                const r = u.bind(null, {
                  resolve: e,
                  reject: t
                });
                n.push(r),
                s.sendMessage(...n)
              }
              ))
            }
```

Hope this can be useful.

BTW, thanks for this extension!

**Comment by HuiiBuh** [comment]
@achillar Yes this helps.
I will update the extension today or tomorrow

**Comment by HuiiBuh** [comment]
I just updated the extension. Could you verify that version 4.4.2 works for you. 
Should take 5 to 10 min until the extension is available in the chrome webstore

**Comment by neelam281181** [comment]
okay

**Comment by Binsy0** [comment]
do I need to reinstall the update as I have the same problem. It wont download anything except as a bulk download which I don't need

**Comment by HuiiBuh** [comment]
if you are using version 4.2.2 everything should work

**Comment by Binsy0** [comment]
i just removed and reinstalled the extension but it is still not working

**Comment by Binsy0** [comment]
yes it is 4.2.2 that is connected

**Comment by HuiiBuh** [comment]
I hate these things. every browser and every browser version behaves differently. What chrome version are you using?

**Comment by Binsy0** [comment]
Version 90.0.4430.93 (Official Build) (64-bit)

**Comment by Gallyi** [comment]
Hi! I'm using Chrome 90.0.4430.93 and Instagram Downloader 4.4.2 (just updated) and I'm not able to download anything at all.
I'm really hoping you could fix it. Cheers!

**Comment by neelam281181** [comment]
Still the problem is same Bro

**Comment by Quark-75** [comment]
Same with Firefox 88, and addon 4.4.1

For some reason it dosen't update the extension as fast on Firefox

**Comment by ultrasahand** [comment]
Chrome Version 90.0.4430.93 (Official Build) (64-bit)
Instagram Downloader 4.4.2

when i click on download icon on Stories a file with the name of insta profile(like "profile_name" downloads with this content
`<!DOCTYPE html>
<body>
<script src="js/background.js"></script>
`
nothing happens when you click on download icon for posts

**Comment by achillar** [comment]
With the last version (4.4.2) I get this error in the extension console:
```
Access to fetch at 'https://instagram.fbru5-1.fna.fbcdn.net/v/t51.2885-15/e35/181938290_305196544506642_255594821480383945_n.jpg?tp=1&_nc_ht=instagram.fbru5-1.fna.fbcdn.net&_nc_cat=1&_nc_ohc=io_eMLONfw0AX98cNWC&edm=AABBvjUBAAAA&ccb=7-4&oh=691017116cc51c7fbf26546d858723a8&oe=60B39F57&_nc_sid=83d603' from origin 'chrome-extension://cpgaheeihidjmolbakklolchdplenjai' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
And then:
```
download.ts:19 GET https://instagram.fbru5-1.fna.fbcdn.net/v/t51.2885-15/e35/181938290_305196544506642_255594821480383945_n.jpg?tp=1&_nc_ht=instagram.fbru5-1.fna.fbcdn.net&_nc_cat=1&_nc_ohc=io_eMLONfw0AX98cNWC&edm=AABBvjUBAAAA&ccb=7-4&oh=691017116cc51c7fbf26546d858723a8&oe=60B39F57&_nc_sid=83d603 net::ERR_FAILED
(anonymous) @ download.ts:19
(anonymous) @ tslib.es6.js:74
__awaiter @ tslib.es6.js:70
downloadSingleImage @ download.ts:14
(anonymous) @ MessageHandler.ts:36
(anonymous) @ tslib.es6.js:74
__awaiter @ tslib.es6.js:70
onMessage @ MessageHandler.ts:34
onMessage @ browser-polyfill.js:1086
```
Not an expert at all in extensions so this could be a silly question: 
Could it be that the extension needs also access to Facebook CDN hosts like 'instagram.fbru5-1.fna.fbcdn.net' besides *://*.cdninstagram.com/* and *://*.instagram.com/* ?

**Comment by HuiiBuh** [comment]
Can anyone try this version. 
I would like to test it before I push another release and unfortunately everything works for me...

[chrome.zip](https://github.com/HuiiBuh/InstagramDownloader/files/6411947/chrome.zip)

**Comment by HuiiBuh** [comment]
Unpack the zip and open in chrome
![image](https://user-images.githubusercontent.com/46561026/116822200-cf2c9800-ab7d-11eb-82ed-aada1bde74de.png)

**Comment by achillar** [comment]
Thanks for your fast answer.

I just installed the unpacked version:

![image](https://user-images.githubusercontent.com/240879/116822480-40207f80-ab7f-11eb-8294-2418b5bf1741.png)

But I am getting a new error message in the console for the page:

```
Uncaught (in promise) Error: Failed to execute 'createObjectURL' on 'URL': Overload resolution failed.
    at wrappedSendMessageCallback (browser-polyfill.js:1158)
```

and the same error message as before in the background page console:

```
Access to fetch at 'https://instagram.fbru5-1.fna.fbcdn.net/v/t51.2885-15/e35/181938290_305196544506642_255594821480383945_n.jpg?tp=1&_nc_ht=instagram.fbru5-1.fna.fbcdn.net&_nc_cat=1&_nc_ohc=io_eMLONfw0AX98cNWC&edm=AABBvjUBAAAA&ccb=7-4&oh=691017116cc51c7fbf26546d858723a8&oe=60B39F57&_nc_sid=83d603' from origin 'chrome-extension://cagnijepclcdpkammmnpnbghfanjnaba' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
download.ts:22 
```

From the look of it, it seems like the fetch is failing like before and the new try using `browser.downloads.download` fails because `URL.createObjectURL` :
```typescript
    let downloadAsset: string | Blob = message.imageURL[0];
    const headers: { name: string; value: string }[] = [];
    try {
        downloadAsset = await (await fetch(message.imageURL[0])).blob();
    } catch {
        if ('browser' in window) headers.push({name: 'Referer', value: 'instagram.com'});
    }

    await browser.downloads.download({
 // ERROR HERE => downloadAsset is the string URL fo the image and URL.createObjectURL seems to expect A File, Blob, or MediaSource object
        url: URL.createObjectURL(downloadAsset),
        filename: imageName,
        headers,
    });
```

**Comment by HuiiBuh** [comment]
Thanks, in this case next try
[chrome.zip](https://github.com/HuiiBuh/InstagramDownloader/files/6412002/chrome.zip)

**Comment by minhanhnguyen2196** [comment]
> Thanks for your fast answer.
> 
> I just installed the unpacked version:
> 
> ![image](https://user-images.githubusercontent.com/240879/116822480-40207f80-ab7f-11eb-8294-2418b5bf1741.png)
> 
> But I am getting a new error message in the console for the page:
> 
> ```
> Uncaught (in promise) Error: Failed to execute 'createObjectURL' on 'URL': Overload resolution failed.
>     at wrappedSendMessageCallback (browser-polyfill.js:1158)
> ```
> 
> and the same error message as before in the background page console:
> 
> ```
> Access to fetch at 'https://instagram.fbru5-1.fna.fbcdn.net/v/t51.2885-15/e35/181938290_305196544506642_255594821480383945_n.jpg?tp=1&_nc_ht=instagram.fbru5-1.fna.fbcdn.net&_nc_cat=1&_nc_ohc=io_eMLONfw0AX98cNWC&edm=AABBvjUBAAAA&ccb=7-4&oh=691017116cc51c7fbf26546d858723a8&oe=60B39F57&_nc_sid=83d603' from origin 'chrome-extension://cagnijepclcdpkammmnpnbghfanjnaba' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
> download.ts:22 
> ```
> 
> From the look of it, it seems like the fetch is failing like before and the new try using `browser.downloads.download` fails because `URL.createObjectURL` :
> 
> ```ts
>     let downloadAsset: string | Blob = message.imageURL[0];
>     const headers: { name: string; value: string }[] = [];
>     try {
>         downloadAsset = await (await fetch(message.imageURL[0])).blob();
>     } catch {
>         if ('browser' in window) headers.push({name: 'Referer', value: 'instagram.com'});
>     }
> 
>     await browser.downloads.download({
>  // ERROR HERE => downloadAsset is the string URL fo the image and URL.createObjectURL seems to expect A File, Blob, or MediaSource object
>         url: URL.createObjectURL(downloadAsset),
>         filename: imageName,
>         headers,
>     });
> ```

same

**Comment by minhanhnguyen2196** [comment]
> Thanks, in this case next try
> [chrome.zip](https://github.com/HuiiBuh/InstagramDownloader/files/6412002/chrome.zip)

Works for me!! Thanks for your quick update
Google Chrome
Version 90.0.4430.93 (Official Build) (64-bit)

**Comment by achillar** [comment]
Also working for me, thanks 👍🏻

**Comment by neelam281181** [comment]
Hey it's working now.... Thanks Bro

**Comment by Binsy0** [comment]
Well done you. All seems to be working. Cheers

**Comment by Binsy0** [comment]
The downloader is not working. same problem as last week.
Regards

**Comment by Binsy0** [comment]
Please ignore previous email
