### ISSUE TITLE
4.4.2 on Chrome occasionally fails to download

### ISSUE THREAD

**Issue by jollino** [HuiiBuh/InstagramDownloader#174]
# Important: Issues without the following information will be closed

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to URL 'https://www.instagram.com/stories/cats_of_instagram/' (video story) or 'https://www.instagram.com/thespacemate/' (picture story) or 'https://www.instagram.com/p/COXMYNQDk4-/' (single post)
2. Click on the profile link to open the stories
3. Try to download
4. Nothing happens

**Expected behaviour**
The story should download.

**Screenshots**
The console shows this for the video story:
![image](https://user-images.githubusercontent.com/3470104/116824392-2d5f7800-ab8a-11eb-9bf2-76f6c4ca7dea.png)
The src URL is https://instagram.fmxp6-1.fna.fbcdn.net/v/t50.2886-16/88643144_1844327559075174_5133498452419614642_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InZ0c192b2RfdXJsZ2VuLjYwOC5zdG9yeS5kZWZhdWx0IiwicWVfZ3JvdXBzIjoiW1wiaWdfd2ViX2RlbGl2ZXJ5X3Z0c19vdGZcIl0ifQ&_nc_ht=instagram.fmxp6-1.fna.fbcdn.net&_nc_cat=106&_nc_ohc=8Jt4OADblBYAX-OEqjN&edm=ANmP7GQBAAAA&vs=17939453026496285_536402086&_nc_vs=HBksFQAYJEdFaVdTQVZtRlFMNVo0MEdBTElYZmRfazJUMUhidXFIQUFBQRUAAsgBABUAGCRHR1B0cUFyaWlwRUNEQU1DQUIySldFc0RyaDhMYnBrd0FBQUYVAgLIAQAoABgAGwGIB3VzZV9vaWwBMRUAACa6uKf4yvXdPxUCKAJDMywXQC4AAAAAAAAYEmRhc2hfYmFzZWxpbmVfMl92MREAdegHAA%3D%3D&ccb=7-4&oe=6090FCA6&oh=56139a5a73cca3487c5793f9d92f7da2&_nc_sid=276363

This for the picture story:
![image](https://user-images.githubusercontent.com/3470104/116824708-ea9e9f80-ab8b-11eb-8b0c-44502b8f348d.png)
The src URL is https://instagram.fmxp6-1.fna.fbcdn.net/v/t51.2885-15/e35/c0.280.720.720a/179896317_106845871471566_6030404973894113246_n.jpg?tp=1&_nc_ht=instagram.fmxp6-1.fna.fbcdn.net&_nc_cat=106&_nc_ohc=7dPAPoQX4h0AX_thkWq&edm=ANmP7GQBAAAA&ccb=7-4&oh=f71a5bdbbdb36d994c9dac6534c2015f&oe=609135CE&_nc_sid=276363&ig_cache_key=MjU2NDI0OTA5MTg4NzI4ODg0Mg%3D%3D.2-ccb7-4

This is for the single post:
![image](https://user-images.githubusercontent.com/3470104/116824688-d195ee80-ab8b-11eb-8c19-8d832a81fa22.png)
mediaURL[0] is "https://instagram.fmxp6-1.fna.fbcdn.net/v/t51.2885-15/e35/181633824_1936086636539555_2168235130080817901_n.jpg?tp=1&_nc_ht=instagram.fmxp6-1.fna.fbcdn.net&_nc_cat=111&_nc_ohc=2aq76ODaHMwAX8zphLc&edm=AABBvjUBAAAA&ccb=7-4&oh=1db3c417f680a09a0eda88b188979c89&oe=60B59EFA&_nc_sid=83d603"

Note that the last fetch error appeared on the others too, but I failed to included it in the screenshots.

**Device:**
- Resolution: 5K (iMac 27")
- Browser: Chrome 90.0.4430.93 (Official Build) (x86_64)
- Extension Version: 4.4.2

**Additional context**
The previous version struggled with downloading stories from close friends, but there was no such fetch error at the time.

Oddly enough, after a few attempts it started working on all sorts of contents (including close-friends stories), and the fetch error disappeared.
I also have uBlock Origin running, but it's still active now that it's started working, so I'm not sure if that is related. Quite baffling!

Let me know if you want me to run any other tests. :) I will add more logs if it happens again.

**Comment by HuiiBuh** [comment]
Hey thanks for the long and detailed bug report.
Did you try Version 4.4.3? I think that I fixed this specific error.

**Comment by jollino** [comment]
Ah sorry, I had tried updating before preparing the report but Chrome hadn't found anything.
Just installed 4.4.3, so far it seems to work. I'll test it more thoroughly tomorrow and post an update.
Thanks!
