### ISSUE TITLE
v4.4.3 - Download Fails - Firefox

### ISSUE THREAD

**Issue by Azureit** [HuiiBuh/InstagramDownloader#175]
Using Firefox, with v4.4.3, all downloads fail.
The request headers to download the files have **origin** set to **moz-extension://1678a753-7d01-42aa-bf6d-0e0cc366f09c**

**Comment by lukew3** [comment]
It works fine for me. I recently had to give extra permissions to the extension though. Do the three bars in the top right of your browser have a notification requesting permissions?

**Comment by HuiiBuh** [comment]
what version are you using?

**Comment by Azureit** [comment]
> what version are you using?

v4.4.3  at Firefox 88.0

This is the Browser console log:
![Screenshot_20210503_084811](https://user-images.githubusercontent.com/1774476/116852870-06865d80-abed-11eb-8983-4f78496192ab.png)

**Comment by Azureit** [comment]
The fix to this, is adding `"*://*.fbcdn.net/*"` to the manifest.json

**Comment by paper9oll** [comment]
Same issue here, is this related to recently closed #165 ? The patch that was implemented work perfectly afterwards but suddenly with the 4.4.3 it stop working again.
