### ISSUE TITLE
A Help Tool To Explain The Permissions

### ISSUE THREAD

**Issue by jayadevanraja** [HuiiBuh/InstagramDownloader#176]
It is extremely useful if there is a help feature, where the rationale behind the permissions is stated. For example, Instagram Downloader asked for permissions regarding something like accessing all data in Instagram CDN (which I did not understand).

A documentation of the rationale behind the permissions is really helpful.

**Comment by HuiiBuh** [comment]
I explained the last permission change in the changelog, so I think this is enough. 
If you want to you can take a look at the changelog in the extension options
