### ISSUE TITLE
Unable to download through Firefox

### ISSUE THREAD

**Issue by clippercord** [HuiiBuh/InstagramDownloader#180]
# Important: Issues without the following information will be closed

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to URL 'https://www.instagram.com/world_record_egg/'
2. Click on download icon
3. See error: 
![Screenshot 2021-05-03 at 08 50 14](https://user-images.githubusercontent.com/83599488/116900003-1ef67800-abed-11eb-89a8-3ac29cc93814.png)
Likely the same issue as #179.

**Expected behaviour**
Expected it to download as usual into Downloads folder.

**Screenshots**
![Screenshot 2021-05-03 at 08 50 14](https://user-images.githubusercontent.com/83599488/116900281-6977f480-abed-11eb-99da-639827b58890.png)

**MacBook Pro running macOS Catalina v. 10.15.7**
- Resolution: [e.g 2K]
- Browser Firefox 88.0 (64-bit)
- Extension Version 4.4.3
![Screenshot 2021-05-03 at 08 50 14](https://user-images.githubusercontent.com/83599488/116900730-eefba480-abed-11eb-9553-d83d9f9ec39d.png)

**Additional context**

**Comment by AndnixSH** [comment]
Same problem on Firefox mobile beta 68.7 but no error appears. It was working perfectly until today

*In case if you are curious, Firefox 68 was the last version it supported non-mobile plugins*

**Comment by clippercord** [comment]
That is interesting to me since I didn’t know there was a mobile version.  However, mine worked great until today.

**Comment by wishusknight** [comment]
If my suspicions are correct, IG is clamping much harder on downloaders. And this sucks. This will be cat and mouse until either the devs for the addons give up, or IG becomes unusable to normal people.

**Comment by FunkyJustin** [comment]
I'm having the same issue as well

**Comment by AlanTheBlank** [comment]
So, if you know how to compile and how to load unsigned plugins I have submitted a pull request #183 which has fixed it.  The issue seems to have been the lack of a user agent
