### ISSUE TITLE
Unable to download multiple pictures from a post

### ISSUE THREAD

**Issue by KlausDint** [HuiiBuh/InstagramDownloader#189]
I'm unable to download posts with multiple pictures. Only the first one will be downloaded.

**Comment by KlausDint** [comment]
# Important: Issues without the following information will be closed

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to URL 'https://www.instagram.com/p/CPQ-_cAMzkY/'
2. Click on the arrows and try to download all pictures from the post
3. See there is no option to download

**Expected behaviour**
A button on every picture of the post to download it.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Device (please complete the following information):**
- Resolution: [e.g 2K] 1920x1080
- Browser [e.g. chrome, firefox] Chrome
- Extension Version [e.g. 4.0.1] 4.4.5

**Additional context**
Add any other context about the problem here.

**Comment by HuiiBuh** [comment]
please send me a Screenshot.
It is working for me
