### ISSUE TITLE
Download by date range

### ISSUE THREAD

**Issue by denchen** [HuiiBuh/InstagramDownloader#190]
It would be nice be able to download posts from a date range. Several use cases:

* I already have half of a my images downloaded. But in several months, I don't want to have to redownload everything, only up to the point where I last downloaded
* I often get kicked out of IG for downloading too many posts. I'm hoping by only downloading small chunks -- like a week's or month's worth -- will alleviate the problem.

**Comment by denchen** [comment]
Also, as an additional feature, it would be nice to have the option of saving files with timestamps, so something like the format:

```
<USER_ID>_<YYYY.MM.DDThh.mm.ss>_<IMAGE_INDEX>.jpg
```
(where `IMAGE_INDEX` is for posts with multiple images)

eg:
```
someuser_2021.05.11T16.48.28_01.jpg
```

**Comment by HuiiBuh** [comment]
Hi.
I am. currently very busy, so I will not be able to implement your feature request.
If you want to create a PR go ahead and do so
