### ISSUE TITLE
Bulk download and file download

### ISSUE THREAD

**Issue by anymza** [HuiiBuh/InstagramDownloader#191]
# Important: Issues without the following information will be closed

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to URL 'https://www.instagram.com/world_record_egg/'
3. See error

**Expected behaviour**

**Screenshots**

**Device (please complete the following information):**
- Resolution: [e.g 2K]
- Browser [e.g. chrome, firefox] Firefox
- Extension Version [e.g. 4.0.1] 4.4.5

**Additional context**
Add any other context about the problem here. Bulk and file download does NOT work since yesterday. Please fix it ASAP becasue I use this add-on a lot everyday. Thank you

**Comment by anymza** [comment]
Hi. I want to know something. Is this addonn anonimous? I mean, does IG or profiles I download know that I´m downloading stories, pictures, videos? I´m asking this because I´ve been having some trouble with my account (I can´t open any profiles) in my PC. I´m a little bit desperate. Thanks

**Comment by HuiiBuh** [comment]
I think Instagram shadow banned you. 
If this is the case the download should start working again after a while
