### ISSUE TITLE
Story download as bulk

### ISSUE THREAD

**Issue by anymza** [HuiiBuh/InstagramDownloader#192]
**Is your feature request related to a problem? Please describe.**
It would be good that stories could be downloaded as bulk

**Comment by HuiiBuh** [comment]
I am afraid this cannot be done, as Instagram prevents me from doing this

**Comment by desbest** [comment]
How does [this chrome extension](https://chrome.google.com/webstore/detail/stories-app-for-instagram/angjmncdicjedpjcapomhnjeinkhdddf) manage to do it?

**Comment by HuiiBuh** [comment]
I would think, that they use an internal api.
This however is not a step I am willing to take
