### ISSUE TITLE
Urgent!! Is this addonn anonimous? 

### ISSUE THREAD

**Issue by anymza** [HuiiBuh/InstagramDownloader#193]
Hi. I want to know something. Is this addonn anonimous? I mean, does IG or profiles I download know that I´m downloading stories, pictures, videos? I´m asking this because I´ve been having some trouble with my account (I can´t open any profiles) in my PC. I´m a little bit desperate. Thanks

_Originally posted by @anymza in https://github.com/HuiiBuh/InstagramDownloader/issues/191#issuecomment-845270280_

**Comment by HuiiBuh** [comment]
No the accounts don't know.
However, if you download to much Instagram may notice

**Comment by anymza** [comment]
Thank you. Do you know of an app or something that can be used to download stories, photes, IGTC, videos, reels, highlights, etc. freely withou being noticed by Instagram and profiles? Thanks again

**Comment by HuiiBuh** [comment]
I am sorry, but I don't really know of anything like this, but I am sure that there are services which provide the service you ask for.

**Comment by HuiiBuh** [comment]
I am sorry, but I don't really know of anything like this, but I am sure
that there are services which provide the service you ask for.
