### ISSUE TITLE
Version 4.4.4

### ISSUE THREAD

**Issue by Nissemus** [HuiiBuh/InstagramDownloader#195]
Could you make version 4.4.4 available for download? Version 4.4.5 seems to be very broken in Firefox for downloading videos and I'd like to try rolling it back.

**Comment by HuiiBuh** [comment]
Just install an old version. The addon store has an addon history where you can install an older version.
But I think this is not the problem of the version change

**Comment by Nissemus** [comment]
You were correct - it didn't help!
