### ISSUE TITLE
Delay for the "Save file as" dialogue box appearing

### ISSUE THREAD

**Issue by jayadevanraja** [HuiiBuh/InstagramDownloader#198]
At times, there is a delay of several seconds or several minutes for the "Save file as" dialogue box appearing.

**To Reproduce**
I am using a random account here. This is not any account which I use.
Steps to reproduce the behaviour:
1. Go to URL 'https://www.instagram.com/p/Bzq941gBZkQ/'
2. Click on the download button
3. It takes a long time (in my case for Firefox, 1 minute 32 seconds and for Chromium it did not appear even after 20 minutes) for the "Save file as" dialogue box to appear. My Ping is 16 ms, Download Mbps is 18.56, Upload Mbps is 20.16.

**Expected behaviour**
"Save file as" dialogue box should appear instantaneously, whatever the size of file being downloaded.

**Device (please complete the following information):**
- Browser Firefox Version 88.0.1, Chromium Version 90.0.4430.212
- Extension Version 4.4.5

**Comment by jayadevanraja** [comment]
After trying multiple times, it works in Chromium, but seems to have the same issue as Firefox. The "Save File As" option takes too much time to appear.

**Comment by HuiiBuh** [comment]
I have also noticed the problem and have already begun to fix the problem

**Comment by wmglock** [comment]
Any progress in fixing the delay ? Why or what is causing the delay ? Thanks

**Comment by HuiiBuh** [comment]
I hope the newest delay will fix this issue
