### ISSUE TITLE
Can't download photos, only stories

### ISSUE THREAD

**Issue by Gallyi** [HuiiBuh/InstagramDownloader#199]
This issue occurred recently, I don't know if the problem is on my end, but I seem to be unable do download photo using the extension, I can only download stories.
I really appreciate the effort you put into the extension and how fast you can fix it.
Thanks!

UPDATE: It seems that the problem is on my end, since I appear to be shadow banned after downloading several photos. I switched to other account and the problem was solved. I just don't know why IG doesn't let me use the extension on my main account since everything indicates that I'm not banned per se.

**Comment by Nazman456** [comment]
I am facing the same issue. I cannot download the pictures with my main account but can download them from another account.
So what can I do in this situation?
Please help me out.

Thanks.

**Comment by HuiiBuh** [comment]
Looks like you got banned. Just wait some. time

**Comment by HuiiBuh** [comment]
Did it start to work again?
Because in this case I will close the issue
