### ISSUE TITLE
Would it be possible to make the shortcut editable?

### ISSUE THREAD

**Issue by topotech** [HuiiBuh/InstagramDownloader#200]
I'm not sure about how Chrome works, but in Firefox it is possible bind shortcuts to certain extension actions and allow users to customize them. Right now, taking over the Ctrl + S clashes with Firefox's default shortcut for screenshots (Ctrl + Shift + S), so it would be nice any option which allows modifying the keys.

Here's an image with how Firefox handles the shortcut customization. Again, I don't know if the Chromium-based browsers have something similar:

![imagen](https://user-images.githubusercontent.com/8272252/119694465-3bb45300-be1b-11eb-9327-761d83b6cbc0.png)

**Comment by HuiiBuh** [comment]
Hi this is possible, however I am currentely very busy and don't have the time for larger feature requests.
If you want to create a PR ease go ahead
