### ISSUE TITLE
Download Instagram Highlight thumbnails

### ISSUE THREAD

**Issue by KlausDint** [HuiiBuh/InstagramDownloader#202]
**Is your feature request related to a problem? Please describe.**
I like to download the Instagram Highlight thumbnails shown on the profile page.

![image](https://user-images.githubusercontent.com/84041609/119813019-168e1600-bee9-11eb-9c6e-533758187081.png)

**Comment by HuiiBuh** [comment]
Sorry, I currently don't have the time for new features. 
If you want to create a PR and add the feature your are more than welcome
