### ISSUE TITLE
Support new Firefox Android Nightly?

### ISSUE THREAD

**Issue by AndnixSH** [HuiiBuh/InstagramDownloader#203]
# Important: Issues without the following information will be closed

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to URL 'https://www.instagram.com/'
2. Download any pics or videos

**Expected behaviour**
Be able to download and save file to device

**Screenshots**
N/A

**Device (please complete the following information):**
- Resolution: 1080 x 2520
- Browser: Firefox Android Nightly
- Extension Version 4.4.6

**Additional context**
I was using Firefox 68 APK on my phone, Instagram downloader works great on it. Reason i use old Firefox because the new Firefox only support very few addons, I can't download addons from the website anymore like I used to do on PC and old Firefox android
As i got a new phone running Android 11, old Firefox is no longer installable so i'm forced to use Firefox Nightly which have expanded extension support
Instagram Downloader can be installed but downloading does nothing, no error or anything. I ran the USB debugger and it seems the extension is working but it's likely not able to access device storage to save
Is there any change you can get it working on Nightly? and maybe publish for Stable version, the official's addon collections?

**Comment by HuiiBuh** [comment]
I do not support the nightly browser.
As soon as Firefox let's the average user install my addon I will fix thr problem.
If you want to fix the problem please create a PR

**Comment by AndnixSH** [comment]
Ok, not a problem. I will find a way to get Firefox 68 to install
