### ISSUE TITLE
Download Content Shared On Chats(Bulk Download and Single Download)

### ISSUE THREAD

**Issue by adityaa-codes** [HuiiBuh/InstagramDownloader#204]
Downloading media directly from chats would be very helpful, currently we have to click on every item and then download, hover download would also work

**Comment by HuiiBuh** [comment]
I will have a look.
If it Is to complicated I will not have the time to add the features otherwise...
Just don't expect anything to soon

**Comment by HuiiBuh** [comment]
Hi, unfortunately I can't get any details of the post in the messenger. 
Therefore I cannot get the images/videos which are linked in the post...
