### ISSUE TITLE
Firefox 89.0

### ISSUE THREAD

**Issue by augstones** [HuiiBuh/InstagramDownloader#207]
Downloads no longer working with Firefox 89.0 - Not sure if this is known issue.

**Comment by Spectroxx** [comment]
It's sporadic on Firefox 89.0, I'm currently on 91.0a1 and it tends to have a long delay before it downloads. You click download once and nothing will happen, click it a few times later you it will download but also download duplicates do to the fact you click it multiple times.

**Comment by augstones** [comment]
Thanks, left it 2 days and its all working now!
