### ISSUE TITLE
File Rename

### ISSUE THREAD

**Issue by amuagarwal** [HuiiBuh/InstagramDownloader#213]
Please do not rename file as it doing now its now more difficult to check duplicate downloads

**Comment by HuiiBuh** [comment]
I preserve the original file name and only attach the username.
I don't change the filename any more

**Comment by amuagarwal** [comment]
but currently the file name getting change every time for the same post

**Comment by HuiiBuh** [comment]
can you give an example?

**Comment by amuagarwal** [comment]
![image](https://user-images.githubusercontent.com/7331483/124118998-95014900-da8f-11eb-85f7-83c93dbcc87f.png)
this is my profile and i am trying to download the post
![image](https://user-images.githubusercontent.com/7331483/124119099-b3ffdb00-da8f-11eb-84eb-d13cfd072d10.png)
above file name on 1st click
![image](https://user-images.githubusercontent.com/7331483/124119128-bf530680-da8f-11eb-8a76-28ae4260a90a.png)
this is on 2nd click
![image](https://user-images.githubusercontent.com/7331483/124119147-c67a1480-da8f-11eb-8ae4-c68e9c9a7590.png)
this is how it showing in download manager. both link are for same post

**Comment by HuiiBuh** [comment]
I tried it with the exact same image and it is working for me.
Do you have any other extensions installed?

**Device (please complete the following information):**
- Resolution: [e.g 2K]
- Browser [e.g. chrome, firefox]
- Extension Version [e.g. 4.0.1]

**Comment by amuagarwal** [comment]
OS: Windows 10
Browser: Chrome v91.0.4472.124
Extension v4.4.7
Laptop Resolution: 1920x1080
Have https://chrome.google.com/webstore/detail/regexp-download-organizer/oamembonjndgangicfphlckkdmagpjlg it use to define the folder to save.
There is no extension related to file renaming

**Comment by amuagarwal** [comment]
got it seems some extension creating issue after disabling all extensions its working
