### ISSUE TITLE
Files no longer contain Instagram username

### ISSUE THREAD

**Issue by Undrhil** [HuiiBuh/InstagramDownloader#214]
# Important: Issues without the following information will be closed

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any Instagram URL
2.  Download image or video
3.  Filename of image or video doesn't contain username of the account downloaded from.

**Expected behaviour**
The filename should contain the Instagram username.

**Device (please complete the following information):**
- Resolution: 1920x1080
- Browser Chrome Version 91.0.4472.124 (Official Build) (64-bit)
- Extension Version 4.4.7

**Comment by HuiiBuh** [comment]
This error is likely associated with another extension which is interfering (At least for the other people this was the problem).

Try disabling the other extensions and if it still does not work please list every extension you have installed, so I can fix the issue

**Comment by Undrhil** [comment]
This appears to be the offending extension: https://chrome.google.com/webstore/detail/twitter-media-assist/cledppeceojodgghbbkaciochldmpdfk

**Comment by HuiiBuh** [comment]
Good to know
