### ISSUE TITLE
Getting Banned Daily 

### ISSUE THREAD

**Issue by dqwerty200** [HuiiBuh/InstagramDownloader#215]
Hi,

Is anyone else getting getting this error message (locked out) lately?

> "We restrict certain activity to protect our community. Based on your use, this action will be unavailable for you until 2021-07-07. Tell us if you think we made a mistake. "

One reason they said I may be getting this error is because my actions appear to be automated by a bot.  Curious to know Instagram knows I am using "InstagramDownloader" and this is why they are locking me out.

Thanks,

**Comment by HuiiBuh** [comment]
You are using the bulk download feature to much.

**Comment by auanasgheps** [comment]
Hi! I got banned as well!
Last time I used the bulk downloaded was 3-4 days ago, only for one account. 
Other than this, I use Instagram normally.

Maybe the extension should download stuff more slowly?

**Comment by rpillala** [comment]
I received this after using the bulk download for the first time today.  I set it to "slow" to be courteous to their servers.  I don't mind waiting for a very slow setting while it works in the background, if it's possible to create something extremely slow.

**Comment by Mitsugoro** [comment]
Hello. I have been banned since yesterday while I was downloading MANUALLY the pics on an account ! How I regret the good old times of the internet...

Hope I will get my account back tomorrow...

**Comment by HuiiBuh** [comment]
This is very unfortunate.
But I don't have the resources to to compete with a player like Facebook, especially if I can maintain this only in my free time.

I will give it another try and hope, that this will work...

**Comment by auanasgheps** [comment]
@HuiiBuh  thank you for supporting this, I just received the update.

Recently [Barinsta](https://github.com/austinhuang0131/austinhuang0131/issues/2), an alternative Instagram client for Android, has received a cease and desist from FB.

One of the reasons is because used the "Instagram" name without authorization. So could be wise to change the name of your extension?

**Comment by auanasgheps** [comment]
Heck, got banned again by manually downloading photos...

**Comment by HuiiBuh** [comment]
What browser are you using?

**Comment by Mitsugoro** [comment]
I use firefox and had the same trouble than auanasgheps.

**Comment by HuiiBuh** [comment]
If all of you are using Firefox this could be the problem. In Firefox I cannot use the native download, so I have to fetch the data manually...

**Comment by auanasgheps** [comment]
I use this extension with Chrome...

**Comment by HuiiBuh** [comment]
Sry. guys. In this case I can't help you.
Perhaps log out of your profile if you download. That's all I can do for you.
I know this sucks, but if IG for. some reason tries to prevent this at all cost I am afraid there is nothing I can do

**Comment by HuiiBuh** [comment]
Hi 
I am closing this for #221
