### ISSUE TITLE
Getting Banned

### ISSUE THREAD

**Issue by HuiiBuh** [HuiiBuh/InstagramDownloader#221]
Unfortunately Instagram is getting more and more aggressive angainst tools like these.
I therefore would advise you to use the bulk download feature with caution. 

I am afraid there is nothing I can do against Instagram blocking you, because I am only a single developer and Instagram is a multi billion dollar company.

**Comment by amuagarwal** [comment]
just a suggestion and random timer for bulk download in addition to slow, fast and normal speed and make it configurable, it will increase the possibility that user not get ban frequently. as same time difference have high possibility to treat extension as bot..

**Comment by DustBytes** [comment]
How to download in bulk?
I can't see that option.

I want to download art pages, which are mentioned to be free and public.

**Comment by HuiiBuh** [comment]
In the menu bar is a download button

**Comment by DustBytes** [comment]
Sorry, can't find any such button.

Where exactly it is?
Which menu.

**Comment by amuagarwal** [comment]
seems there is some changes in DOM by Instagram so as of now its not anywhere visible only individual download button is available.

**Comment by amuagarwal** [comment]
one more suggestion to stop banning is when you collect the list of post just keep it and split in random bunch like bunch of 10/20 or any random number. and download it with random time interval as its easy if the time interval is fixed to detect the ban. even i face it for 3 times

**Comment by jollino** [comment]
I never use the bulk download feature, just occasionally save photos manually (maybe a dozen a week or so). Still, I've been getting notifications about my account being potentially compromised and being temporarily locked out, and I've been wondering if it's due to those downloads.
I'm otherwise a very light user on instagram these days (in fact I have only been lurking for a while, not really posting anything) and mostly use the messaging feature with people I've known for years, so the only "odd" thing is really these downloads using the extension. Even when I access the site from desktop, it's from the same IP as I use on my phone so it's not an issue of "you showed up from two different places at the same time". This is also happening on both my accounts, which both have the extension.
Has anyone else had the same experience?

**Comment by HuiiBuh** [comment]
I have heard of similar behavior and the issue may very well be connected with the extension.

**Comment by christoarmani** [comment]
Instagram reduced the number of requests per hour from 1000 to 200. With that said, Instagram seems to know when you are using automated tools to collect content. According to Instagram's [Terms of Use](https://help.instagram.com/581066165581870/?helpref=hc_fnav) in Your Commitments: "You can't attempt to create accounts or access or collect information in unauthorized ways. This includes creating accounts or collecting information in an automated way without our express permission." 

In recent years/months Instagram has been really cracking down on tools that collect content. It also appears that with new profiles they can detect automation quicker. I am not sure if there is any way around this other than creating your own API following their guidelines: https://developers.facebook.com/docs/instagram-api/

This doesn't answer your question but I thought I would share some of my findings on this.

**Comment by tbertels** [comment]
If it is indeed 200 requests per hour ([that's the case for the graph API](https://developers.facebook.com/docs/graph-api/overview/rate-limiting#platform-rate-limits)), then the current Low rate is way too high.
Based on https://github.com/HuiiBuh/InstagramDownloader/blob/9db135f4f0d73159ea672262cb17c573c126de0c/src/ts/downloaders/BulkDownloader.ts#L163 (where downloadSpeed is 3 in High and 1 in Slow) it's 6 seconds for one screen height scroll.
But:
* it seems much faster than that (at least on Firefox).
* it's way too high: one screen height is at least 6 requests (more when there are multiple media per post), which means 3600 requests per hour vs 200 requests per hour = 18 seconds per request
* once the page is scrolled, the download begins. Does that count also in requests? In that case, it should be reduced too.

**Comment by HuiiBuh** [comment]
Bulk has been removed because IG blocked it completely. I will therefore close this issue
