### ISSUE TITLE
Filename starting with date derived from media id

### ISSUE THREAD

**Issue by Azureit** [HuiiBuh/InstagramDownloader#223]
To better organize downloaded files sorted, filename could start with YYYY-MM-DD_HH.MM.SS 
To get date without need to do more downloads, derive the date from media id.

e.g. https://www.instagram.com/p/CTFlHsmpEVW/
1) convert shortcode to id:  CTFlHsmpEVW -> 2649687212427593046
2) convert id to timestamp: 2649687212427593046 / 2^23 + 1314220021721 = 1630087351846
3) convert timestamp to the user local timezone: 1630087351846 -> Friday, 27 August 2021 19:02:31.846 GMT+01:00 DST
Now the filename could start with "2021-08-27_19.02.31" for better organization and sorting.
In this case the https://www.instagram.com/p/CTFlHsmpEVW/ would be downloaded to filename "2021-08-27_19.02.31_instagram.mp4"

**Comment by HuiiBuh** [comment]
How would you convert the shortcode to the ID?
Is the ID the ASCII representation?

**Comment by Azureit** [comment]
> How would you convert the shortcode to the ID?
> Is the ID the ASCII representation?

Something like this:
```
function shortcodeToInstaID(Shortcode) {
      var char;
      var id = 0;
      var alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_';
      for (var i = 0; i < Shortcode.length; i++) {
          char = Shortcode[i];
          id = (id * 64) + alphabet.indexOf(char);
      }
      return id;
}
```

**Comment by f0rr357** [comment]
>       for (var i = 0; i < Shortcode.length; i++) {
>           char = Shortcode[i];

Here you meant "id" right? Otherwise id will always be 0

function shortcodeToInstaID(Shortcode) {
      var char;
      var id = 0;
      var alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_';
      for (var id = 0; id < Shortcode.length; id++) {
          char = Shortcode[id];
          id = (id * 64) + alphabet.indexOf(char);
      }
      return id;
}

**Comment by Azureit** [comment]
> > ```
> >   for (var i = 0; i < Shortcode.length; i++) {
> >       char = Shortcode[i];
> > ```
> 
> Here you meant "id" right? Otherwise wouldn't id always be 0 in (id*64)?
> 
That part is to loop the Shortcode characters, instead we could rewrite "for (let char of Shortcode) {"
It's not always zero, because you add the index of the char in the alphabet variable

As an example, take the Shortcode "CTFlHsmpEVW"
0 * 64 + 2 = 2
2 * 64 + 19 = 147
147 * 64 + 5 = 9413
9413 * 64 + 37 = 602469
602469 * 64 + 7 = 38558023
38558023 * 64 + 44 = 2467713516
2467713516 * 64 + 38 = 157933665062
157933665062 * 64 + 41 = 10107754564009
10107754564009 * 64 + 4 = 646896292096580
646896292096580 * 64 + 21 = 41401362694181141
41401362694181141 * 64 + 22 = 2649687212427593046

======================================================================
The javascript function I posted is not mine. I now tested it and it's not precise, to be precise you have to use Bigint

```
function shortcodeToInstaID(Shortcode) {
      const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_';
      var id = 0n;
      for (let char of Shortcode) {
          id = (id * 64n) + BigInt(alphabet.indexOf(char));
      }
      return id;
}

**Comment by Kuba4ful** [comment]
If you introduce it, please add an option to keep legacy saving names. Not only is this feature redundant to me, it will mess with the collection I already have (thanks to instagram's media ids always rising, the media are always sorted chronologically). 

And if you do introduce it, also keep the file starting with creator's account name, as it helps much more with sorting than starting from date.

I think the best possible solution would be to let every user set their own saving pattern names, similar to how Puush/ShareX did it.

**Comment by HuiiBuh** [comment]
I have been delaying this feature, because of this exact reason.
I will not start adding settings to the extension, because this would just add unnecessary complexity. How about the timestamp at the end?
Would this work for all of you?

**Comment by Azureit** [comment]
> How about the timestamp at the end? Would this work for all of you?

It works for me, I would use a bash script to mass rename how I want.

Not a issue for me, but the filename would become too big, perhaps you could remove parts of filename that don't add info about the file.

**Comment by HuiiBuh** [comment]
I will not change this. Just to much work and I am sure that I will get issues if I change anything
