### ISSUE TITLE
Filenames/metadata derived from post descriptions or hashtags?

### ISSUE THREAD

**Issue by tealjmoon** [HuiiBuh/InstagramDownloader#224]
Hi thanks for your excellent work!

Do you think we could get filenames derived from post descriptions or hashtags, or to have that information added to the metadata tag somehow?

I'm downloading huge educational archives and sorting them one by one is just not viable

Thank you so much

**Comment by HuiiBuh** [comment]
I think this will not be a thing. The file names would just get to long and unusable
