### ISSUE TITLE
Any chance that your project has been compromised?

### ISSUE THREAD

**Issue by soundstage** [HuiiBuh/InstagramDownloader#225]
Ever since I got this pop-up from your extension some 2 to 3 days ago, [https://huiibuh.github.io/InstagramDownloader/changelog/](https://huiibuh.github.io/InstagramDownloader/changelog/), my PC has been plagued by Cryptojacking freezes, crashes and black screen of death.

I am not absolutely sure that your extension is the reason for such behaviour, so I am getting in touch with all extension developers who recently, in a time frame of 4 to 7 days, released any update to report such issue directly to the developers.

In the interest of many people who are using your extension and for giving you the benefit of doubt, please check if your extension has been compromised. I am facing this issue on Chrome, Windows 10.

**Comment by HuiiBuh** [comment]
Pretty shure no.
The last release was made by me.
If you want to assure yourself, go to the actions tab and view the workflow which uploads the files after build directly from github

**Comment by HuiiBuh** [comment]
So you can be sure that I don't tamper with anything after I publish the extension
