### ISSUE TITLE
DL icon doesnt show in stories

### ISSUE THREAD

**Issue by allonp** [HuiiBuh/InstagramDownloader#226]
# Important: Issues without the following information will be closed

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to URL 'https://www.instagram.com/world_record_egg/'
3. See error

**Expected behaviour**

**Screenshots**

**Device (please complete the following information):**
- Resolution: [e.g 2K]
- Browser [e.g. chrome, firefox]
- Extension Version [e.g. 4.0.1]

**Additional context**

**Comment by HuiiBuh** [comment]
No info provided

**Comment by Erdi2609** [comment]
I have the same issue, using Firefox 92.0 on Windows 10

**Comment by HuiiBuh** [comment]
info?

**Comment by allonp** [comment]
chrome
windows 10
![Untitled](https://user-images.githubusercontent.com/73233409/133308641-5f2d3e05-065b-449a-a72c-86679f288818.png)

**Comment by allonp** [comment]
there should be the download icon near the X
uninsatalling and  reinstalling did not help

**Comment by Erdi2609** [comment]
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to URL https://www.instagram.com/stories/instagram/
2. See that download-button is missing

**Expected behaviour**
download-button visible

**Screenshots**
![image](https://user-images.githubusercontent.com/50457271/133308668-0877d120-e448-4b5d-aba5-aefc3f6e4ce3.png)


**Device (please complete the following information):**
- Resolution: 1K
- Browser Firefox
- Extension Version 4.5.1

**Additional context**
Was working until yesterday

**Comment by HuiiBuh** [comment]
thanks I will have a look at it

**Comment by allonp** [comment]
was waorking until about an hour ago
all other features working

**Comment by gt197121** [comment]
I have same issue in Chrome, download icon shows on images but not stories

**Comment by Gallyi** [comment]
Same issue as everyone reported (Chrome  93.0.4577.82), Win10 (just updated)

**Comment by paper9oll** [comment]
Same issues here. Tried on Firefox v92.0 (64-bit), Microsoft Edge v93.0, and Google Chrome v93.0.

The download button shows in posts, profile picture, the navigation bar but not in stories.

**Comment by bhairabc** [comment]
This is because Instagram has changed the selector for the Story Close button. The current selector it seems is `.aUIsh`.

**Comment by bhairabc** [comment]
> 
> 
> thanks I will have a look at it

It seems Instagram has changed the selector for the Story Close button. The current selector it seems is `.aUIsh`.

**Comment by HuiiBuh** [comment]
just updated the version. 
firefox users can already try it out

**Comment by allonp** [comment]
it's working
thanks
