### ISSUE TITLE
Story download is not working

### ISSUE THREAD

**Issue by anymza** [HuiiBuh/InstagramDownloader#228]
Hello everyone.
I want to report an issue with the tool for downloading IG stories. The icon (arrow at the right side of the screen) is not available. I find this Firefox add-on tool very usefull since it´s the only one that allows me to download video stories. I hope you can help me out soon. 
Thank you in advance

**Comment by hyunbb** [comment]
The edge browser also doesn't work...

**Comment by paper9oll** [comment]
Duplicate of #226
