### ISSUE TITLE
Download post button not working

### ISSUE THREAD

**Issue by AlexJota11** [HuiiBuh/InstagramDownloader#231]
# Important: Issues without the following information will be closed

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to URL 'https://www.instagram.com/world_record_egg/'
2. Click on 'download post'
3. See error

**Expected behaviour**
The download button on posts isn't working for me. It still works on stories.

**Device (please complete the following information):**
- Resolution: [1920*1080]
- Browser [Chrome & Edge]
- Extension Version [4.5.2]

**Comment by leojimenezcr** [comment]
It's not working for me either:
- Browser: [Mozilla Firefox for Ubuntu 93.0]
- Extension Version: [4.5.2]

Tested on:
- Image in the timeline (failed)
- Image of a post (failed)
- Video in the timeline (failed)
- Video of a post (failed)
- Story (working)

In all cases the Firefox console indicates:
`TypeError: (intermediate value).graphql is undefined` [[know more](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Errors/Unexpected_type?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default)]
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://graph.instagram.com/logging_client_events. (Reason: CORS request did not succeed).` [[know more](https://developer.mozilla.org/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed?utm_source=devtools&utm_medium=firefox-cors-errors&utm_campaign=default)]

**Comment by anton-valeryevich** [comment]
Та же проблема.

**Comment by HuiiBuh** [comment]
Can someone past the body, or create a PR with the new query selector?
It is unfortunately still working for me

**Comment by leojimenezcr** [comment]
I tried again. But without being authenticated. This way it worked.

- Browser: [Mozilla Firefox for Ubuntu 93.0]
- Extension Version: [4.5.2]
