### ISSUE TITLE
Download button not working except in stories

### ISSUE THREAD

**Issue by Leyewho** [HuiiBuh/InstagramDownloader#233]
# Important: Issues without the following information will be closed

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to URL 'https://www.instagram.com/world_record_egg/'
2. Click to download
3. Nothing happens, no pop upm window to ask where to download or anything of the sort

**Expected behaviour**
Supposed to allow you to download from instagram but ATM it does nothing

**Screenshots**
No point in adding a screen of the mouse over the download button as there is no error message

**Device (please complete the following information):**
- Resolution: [e.g 2K] 1080p
- Browser [e.g. chrome, firefox] Chrome
- Extension Version 4.5.2

**Additional context**
Funnily enough I tested by adding a story and clicking the download button while in the story and it does download that image, but it is the only download button that works

**Comment by Mitchfynde** [comment]
It's the same for me. It only works in the stories. Nothing pops up at all anywhere else.

**Comment by Leyewho** [comment]
> Can you past a screenshot of the console after you click the download button
> 
> And please try to download after you logged out of your account and tell me if the download still works

I honestly do not know how to download after logging off, when I go to any insta link while logged off, it takes me to the login screen

Now, as far as I see, there is no change in the console when clicking the button
![image](https://user-images.githubusercontent.com/74164402/137184493-bd85eebb-8930-426d-a4f9-7cac48afa4e3.png)

I also did a test and downloaded firefox and installed this extension and it was the same, it does not work in FF except with stories

**Comment by HuiiBuh** [comment]
Thanks for your screenshots. 
The with timeout is just a debug information which says that the buttons where added with a timeout, because the page render was not fast enough.

I am currently use an unprotected IG api to download the posts. It looks like the API might be about to get protected and some of you cannot access it any more. 

Please visit a post and past the following js in the console and send me the result.
Please be aware that this will reveal some information, so don't do this on your private account, but on some public account.
```javascript
const response = await (await fetch(`${window.location.href}?__a=1`)).json()
console.log(response)
```
After that I will (hopefully) know what the problem is.

**Comment by HuiiBuh** [comment]
Just visit any public account post like this one.
https://www.instagram.com/p/CURlyEsKrMn/
This does not reveal anything about you. Just about the page you are currently visiting

**Comment by HuiiBuh** [comment]
Thanks. This looks like it should work. Strange that it does not....

**Comment by Leyewho** [comment]
Yes, I just tested it again and it is working once more, I guess unless you have something to add HuiiBuh then we can close the ticket and if it happens again then  we know what to do and we open another ticket with the info :)

**Comment by Fergo** [comment]
Having the same issue. 

When logged in, the JSON returned by `${contentURL}?__a=1` is not in the GraphQL format, so `graphql.shortcode_media` doesn't exists. When logged in, the code is available at `items[0].code`.
