### ISSUE TITLE
(Firefox version) Downloads are going to a temp folder on my SSD first, then getting moved to the downloads folder

### ISSUE THREAD

**Issue by ashamefuldog** [HuiiBuh/InstagramDownloader#234]
The issue is that when I download a story or something on Firefox through the extension, it seems like it isn't downloaded to Firefox's usual download directory... I'm not sure WHERE it's going, actually, I can just see that it's being written somewhere to my SSD instead of my ramdrive where my downloads normally go, then getting moved over once the download is finished, which is putting a bunch of unnecessary writes on the SSD. My other downloads go straight to the ramdrive where they're supposed to, so it seems like it's just this extension. 

Anyway, this isn't a huge problem if you're only downloading pictures, obviously, but once in a while I download a bigass multi-gigabyte IGTV story, and I'd really prefer those go straight to my usual download directory instead of eating up writes on my main drive. I installed and checked the Chrome version and apparently this isn't a problem there, was just hoping to get a Firefox fix at some point since that's my preferred browser.

**Comment by HuiiBuh** [comment]
Hi you can change this behavior in your settings. I cannot control where the download will happen. Please enable the save as dialog in the Firefox settings.
If you are not sure where it is downloading the file you can check the download history in Firefox and find the file that way
