### ISSUE TITLE
Seems to have become disabled on 11/10/21

### ISSUE THREAD

**Issue by ninja-pimp** [HuiiBuh/InstagramDownloader#237]
A FF (94.0.1) on Win10 user but it seems to have stopped working today sometime after 1200Z .  Loaded it up in Chrome as well and getting the same results..

Steps to reproduce the behaviour:
1. Go to URL 'https://www.instagram.com/world_record_egg/'
2. Click on any image and then click the DL icon
3.  Nothing happens

Device (please complete the following information):**
- Resolution: 1920
- Browser FF 94.0.1  and Chrome 95.0.4638.69 IGD  on Win10
- Extension Version 4.5.3 for both browsers

**Comment by ninja-pimp** [comment]
I noted the time since it was working earlier in the day.

**Comment by HuiiBuh** [comment]
Hi, 
it is unfortunately working for me. 
Can you clear the console of the browser, click the download and check if there have been any new messages in the console?

**Comment by ninja-pimp** [comment]
Thanks HuiiBuh.   You are correct, all is good.
It is working now, and not sure went nuts on my end (other than me being a dummy).

Sorry about the bad bug report and thank you for the excellent product!!!

**Comment by ninja-pimp** [comment]
Thanks HuiiBuh. You are correct, all is good.
It is working now, and not sure went nuts on my end (other than me being a dummy).
