### ISSUE TITLE
Can't download closed friends stories on Firefox

### ISSUE THREAD

**Issue by Kuba4ful** [HuiiBuh/InstagramDownloader#239]
**To Reproduce**
1. Go to any story marked with Closed Friends (colored green)
2. Click on download button
3. Nothing happens(?)

**Expected behavior**
A story is supposed to be downloaded.

**Screenshots**
No screenshots, but I copied the console output:

`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

It outputs it every single time after pressing either the download button, or ctrl+s.

**Device (please complete the following information):**
- Firefox 94.01
- Newest extension version

**Additional context**
Everything else works fine, asides from downloading closed friends stories.

Also, just tested, I follow two people who upload things to Closed Friends stories. I can download stories from the first person fine, but I can't from the second person. 

The only difference between those two accounts is that the first one uploaded normal story + closed friends story, but the second one only closed friends story. I don't know if that's the reason, but I'm just throwing out clues. Also the second person uploaded the photo with instagram music, which isn't available in my region, but I don't think that's the reason why.

**Comment by HuiiBuh** [comment]
Are there any other messages in the console?
