### ISSUE TITLE
Yesterday my download button disappeared from both browsers that I am using for an unknown reason

### ISSUE THREAD

**Issue by esave69** [HuiiBuh/InstagramDownloader#240]
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to URL 'https://www.instagram.com/world_record_egg/'
2. See error

**Expected behaviour**
There should be the download button beside home button.

**Screenshots**
No screenshots.

**Device:**
- Screen resolution: 1366x768; 2520x1080
- Browsers: Chrome, Firefox
- Extension Version 4.5.3

**Additional context**
I tried to restart my PC and reinstall the extension. I have no idea what happened. I have been using the extension for a long time and have downloaded a lot of Instagram accounts.

**Comment by crossfire27** [comment]
same here

**Comment by Jimbozinya** [comment]
I'm experiencing the same issue.

**Comment by HuiiBuh** [comment]
Already fixed it.
Will update tomorrow

**Comment by ctc1112** [comment]
@HuiiBuh still having the same issue, reinstalled the extension and restarted my pc to no avail. Please advise how to get the download button back for gallery. :)

**Comment by Jimbozinya** [comment]
> @HuiiBuh still having the same issue, reinstalled the extension and restarted my pc to no avail. Please advise how to get the download button back for gallery. :)

Same here

**Comment by esave69** [comment]
> @HuiiBuh still having the same issue, reinstalled the extension and restarted my pc to no avail. Please advise how to get the download button back for gallery. :)

I downloaded a couple of accounts and then it started to download empty archives :(

**Comment by HuiiBuh** [comment]
Looks like Instagram found out and blocked you ;)

It is getting harder and harder to hide such activities, so I  am afraid there is nothing I can do

**Comment by esave69** [comment]
> Looks like Instagram found out and blocked you ;)
> 
> It is getting harder and harder to hide such activities, so I am afraid there is nothing I can do

Not yet

**Comment by desbest** [comment]
For starters if Instagram is going to keep trying to block extension like these, I wouldn’t have it be open source on GitHub.
