### ISSUE TITLE
chrome web store not updated, how to install this extension manually?

### ISSUE THREAD

**Issue by crossfire27** [HuiiBuh/InstagramDownloader#241]
# Important: Issues without the following information will be closed

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to URL 'https://www.instagram.com/world_record_egg/'
3. See error

**Expected behaviour**

**Screenshots**

**Device (please complete the following information):**
- Resolution: [e.g 2K]
- Browser  chrome
- Extension Version 4.5.3

**Additional context**
I have a question, how am I supposed to install this extension manually, since chrome web store is not updated? Can You provide the guide for the manual installation process?

**Comment by HuiiBuh** [comment]
It takes time...
