### ISSUE TITLE
Extension doesn't remenber the folder you last donwloaded to.

### ISSUE THREAD

**Issue by NeoFahrenheit** [HuiiBuh/InstagramDownloader#245]
Hi,

I'm using Windows 10 and Chrome and the extension always opens in the *Downloads* folder when I try to download something, not matter what folder I downloaded to before. In any other software, I expect the software to remenber (or Windows, I don't know) such folder so I don't have the need to navigating there or copyng and pasting adress on the path bar.

Thank you. :)

**Comment by HuiiBuh** [comment]
No can do.
This is up to you
