### ISSUE TITLE
Firefox Addon no longer availible

### ISSUE THREAD

**Issue by Spectroxx** [HuiiBuh/InstagramDownloader#246]
Please refer to:
https://addons.mozilla.org/en-GB/firefox/addon/instagram_download/

**Comment by fabio841** [comment]
Hi staff upload xpi file pls

**Comment by Spectroxx** [comment]
@HuiiBuh Was it taken down by Mozilla or did you remove it?

**Comment by HuiiBuh** [comment]
Mozilla could not verify my build. I really don't know why. I wrote them that the build is automated with an github action to avoid someone tampering with the code, but they still did not seem satisfied.

I will try to publish a new version. Perhaps this will help

**Comment by Spectroxx** [comment]
> Mozilla could not verify my build. I really don't know why. I wrote them that the build is automated with an github action to avoid someone tampering with the code, but they still did not seem satisfied.
> 
> I will try to publish a new version. Perhaps this will help

Thanks for the response! Hopefully it will go through this time

**Comment by fabio841** [comment]
If you can upload xpi file last version here. I can open by browser and start local install

**Comment by HuiiBuh** [comment]
Just uploaded the new version. 
Hopefully the review process will go smoother this time.

@fabio841 Here you go. 


[chrome.zip](https://github.com/HuiiBuh/InstagramDownloader/files/7833854/chrome.zip)
[firefox.zip](https://github.com/HuiiBuh/InstagramDownloader/files/7833855/firefox.zip)

**Comment by fabio841** [comment]
Very thanks. Buy this not a .xpi file. How install this zip into Firefox mobile ? Thanks

Inviata dal mio dispositivo Android.

-----Original Message-----

**Comment by Spectroxx** [comment]
> Very thanks. Buy this not a .xpi file. How install this zip into Firefox mobile ? Thanks Inviata dal mio dispositivo Android.

Just replace the .zip for .xpi as the file extension.

**Comment by fabio841** [comment]
I have rename file. When open with Firefox have message that component not have sign and lock install

Inviata dal mio dispositivo Android.

-----Original Message-----

**Comment by HuiiBuh** [comment]
Only Mozilla can sign that extension.
I. This case just wait until it was approved

**Comment by HuiiBuh** [comment]
Good news.
The Lin was just published
