### ISSUE TITLE
Please update the firefox addon link

### ISSUE THREAD

**Issue by binit-thapa** [HuiiBuh/InstagramDownloader#248]
The firefox addon link on the Readme page is wrong, Please update to the correct one,
This is the current one and doesn't work:
https://addons.mozilla.org/en-GB/firefox/addon/instagram_download/

This is the correct one (I guess).
https://addons.mozilla.org/en-US/firefox/addon/fastsave-for-instagram/

(PS: its the best addon I've tried so far).

**Comment by HuiiBuh** [comment]
Nope. 
Not associated with me. 
Please be aware that this extension could steal your information (not open source)
