### ISSUE TITLE
Extension not updated on Chrome Web Store

### ISSUE THREAD

**Issue by edge261** [HuiiBuh/InstagramDownloader#249]
As the title says. the extension is not updated on the Chrome Web Store, being 4.5.5 the latest version there.
https://chrome.google.com/webstore/detail/ig-downloader/cpgaheeihidjmolbakklolchdplenjai

**Comment by HuiiBuh** [comment]
Honesty. You are not missing out.
I only updated Firefox, because there was a problem with the review process.
