### ISSUE TITLE
Download icon not functioning (j/s error)

### ISSUE THREAD

**Issue by mcrib96** [HuiiBuh/InstagramDownloader#251]
Not sure if Instagram changed something or if Chrome did, but I am now getting this javascript error and files will not download:
![image](https://user-images.githubusercontent.com/26966537/150230557-c9158be2-e074-4eb7-9012-d463908c6297.png)

Chrome: v97.0.4692.71
Extension: v2.1

**Comment by HuiiBuh** [comment]
If you are really using v2.1 you should update to v4

**Comment by SnowNooDLe** [comment]
> If you are really using v2.1 you should update to v4

Thanks, I didn't even know there was a newer version.

@mcrib96 Check out the ReadME and the link will redirect you to the extension store with V4 👍

**Comment by mcrib96** [comment]
@HuiiBuh: I didn't know the extension was renamed!

The current version of FastSave for Instagram lists version 2.1 as the current version.
Using the most current version of IG Downloader fixes my issue.

It would be helpful for other users to have a link to the new extension on the FastSave for Instagram extension page in the Chrome extension store.

**Comment by HuiiBuh** [comment]
This is not an extension I am distributing.
They just stole my code. This extension may sell your data.
