### ISSUE TITLE
Please add a "download all pics" button for a single post

### ISSUE THREAD

**Issue by dante987** [HuiiBuh/InstagramDownloader#252]
If a post has more than 1 photo (say 5-6 photos), can you please add a button to download all the pics in that post alone all at once ? Right now if we click on the download arrow, only the first pic is downloaded and we have to individually download each pic in that post which is very time consuming. 
Can you please add a "download all pics" button for a single post. :)

**Comment by HuiiBuh** [comment]
Control + s

**Comment by dante987** [comment]
1) oh ok. 
But that means we have to open each "multiple pics post" in a new tab and then press "Control+s" right ? Pressing "Control+s" on a profile just asks to download the whole webpage.

2) Also, when using "Control+s" properly (i.e. in a new tab), the extracted files don't have the profile name in front of them like when we download a single pic post. 
Example:
Downloading "https://www.instagram.com/p/CXKQ86Dps0H/" we get
263871205_442938027268134_3664071965245975377_n
instead of
nasa_263871205_442938027268134_3664071965245975377_n
Can you please make it so that profile names are added in front. :)

3) The download button I was mentioning in my original post was something like this "zip" option you can see in the attached image. It will save time since we dont have to open in a new tab and press "Control+s"

![zip download if possible please](https://user-images.githubusercontent.com/55316326/150555795-5fa2b69e-42ba-4962-b908-06ea0915e6e7.jpg)
