### ISSUE TITLE
This extension does not give the highest quality Instagram story

### ISSUE THREAD

**Issue by dante987** [HuiiBuh/InstagramDownloader#253]
Unfortunately this extension DOES NOT give the highest quality Instagram story. Posts are fine but stories are sometimes of lower resolution/quality.
Example:
Lets download a story say "https://www.instagram.com/stories/highlights/17938341550761454/"

The downloaded story from this extension:
samsung_266846341_1061409804402860_7048794707254543422_n
[170 kb 750x1333]

Now if you download the same story from this site: "https://instafinsta.com/instagram-highlights-download"
The downloaded story from this site:
266846341_1061409804402860_7048794707254543422_n
[263 kb 1080x1920]

But wait, there's more.
I also use an extension which is now removed from store. Its called "Browser Downloader for Instagram". Here it is "https://chrome-stats.com/d/nmedelcgkdlcedogdcdgnncdcecolpib"
The same downloaded story from this extension:
samsung_266846341_1061409804402860_7048794707254543422_n
[275 kb 1125x2000] *** the best quality/resolution story download ***

One thing to note though. If you use this extension that I gave you (Browser Downloader for Instagram) and download a story that is a video, sometimes the downloaded video is of low quality. When that is the case, I use "https://instafinsta.com/insta-stories-download" and get a better quality video story. When a story is an image, I use "Browser Downloader for Instagram".

So here is the recap.
If Instagram story is image, I use "Browser Downloader for Instagram".
If Instagram story is video, I use "https://instafinsta.com/insta-stories-download".

Can you please update your extension so that we get the best quality story(image/video) as well. :)

**Device: Windows 10 x64 pc**
- Resolution: 4k
- Browser: Opera
- Extension Version 4.5.5

**Comment by HuiiBuh** [comment]
I would think that they use some kind of internal API.
I will not reverse engineer the IG api, because this is (in my opinion) just too intrusive.
