### ISSUE TITLE
Conflict with another extension

### ISSUE THREAD

**Issue by dante987** [HuiiBuh/InstagramDownloader#254]
Whenever this extension is enabled with Imagus extension (https://chrome.google.com/webstore/detail/imagus/immpkjjlgappgfkkfieppnmlhakdmaab), we are unable to download any story. Posts are downloaded fine, but no story is downloaded.

Using Imagus extension, when we place our mouse cursor over a post it enlarges the thumbnails so we can see the image/video full screen. So, we don't have to click. Also we don't have to click next if there are multiple pics in a single post, we can just use mouse scroll wheel or arrow buttons.
Please look into this if possible. Both these extensions are useful and I wish there was no conflict and they both worked fine at the same time.

**Device: Windows 10 x64 pc**
- Resolution: 4k
- Browser: Opera
- Extension Version: 4.5.5

**Comment by HuiiBuh** [comment]
I will not maintain compatability with other extensions. These can add breaking changes every time and it is just to much work for me (I dont get paid...)

If you want to create a PR, I would be happy to merge it
