### ISSUE TITLE
Extension doesn't download all the content of a post

### ISSUE THREAD

**Issue by Beast2000** [HuiiBuh/InstagramDownloader#257]
If a post has more than one photo/video in it, it only downloads the first photo/video of that post instead of all the photos/videos of that certain post. Fix it asap my man!

**Comment by HuiiBuh** [comment]
Honestly, I don't think I will.
I do this in my free time and don't get money for maintaining the extension.

So when someone comes and demands that I fix something asap I always have a problem with that. But if this person does not even fill in the template I provide for filing a bug report... Idk. Then my motivation level is very, very low.

**Comment by HuiiBuh** [comment]
If you want me to fix it provide at least the information I request in the form for filing a bug report

**Comment by Beast2000** [comment]
Where is the Bug Report Form, man?
I am new in Github :(

**Comment by Beast2000** [comment]
Okay I got it. On it
