### ISSUE TITLE
Extension doesn't download all the content of a post and downloads only the first content

### ISSUE THREAD

**Issue by Beast2000** [HuiiBuh/InstagramDownloader#258]
# Important: Issues without the following information will be closed

**To Reproduce**
Steps to reproduce the behaviour:
1. Make sure that the extension is installed in your browser.
2. Go to URL 'https://www.instagram.com/eminem/'
2. Select a post that has more than one content in it. Like a post having two photos,  or three videos, or one photo and 2 videos etc.
3. Hover the mouse over the post and click the download button."
4. See the problem, where the extension only downloads the first/cover content of the post and doesn't download the other content at all.

**Expected behaviour**
If a post has more than one photo/video in it, it only downloads the first photo/video of that post instead of all the photos/videos of that certain post.

**Screenshots**
![1](https://user-images.githubusercontent.com/98300736/150743082-2ce01ad7-f9ed-45a4-8ec4-538ffad84d58.png)
![2](https://user-images.githubusercontent.com/98300736/150743177-5b59d5c2-b4d9-4e70-85aa-c5bfefe8faae.png)
![3](https://user-images.githubusercontent.com/98300736/150743208-62f174f9-6834-4c4c-aca0-3d81104f8467.png)
![4](https://user-images.githubusercontent.com/98300736/150743228-aba6be6a-e212-4104-ab57-47acf7617f7e.png)

**Device**
- Resolution: 1920X1080
- Browser: Microsoft Edge
- Extension Version: 4.5.5

**Additional context**

**Comment by HuiiBuh** [comment]
Thanks for your detailed write up. 
The new version will fix this issue
