### ISSUE TITLE
Does not download always.

### ISSUE THREAD

**Issue by gidbrowser** [HuiiBuh/InstagramDownloader#261]
Sometimes when I wanna bulk download a whole profile (it has many images 500-1000+) The tool goes through all images as usual, but instantly finishes the download and I end up with a zip that is 22kb.

If I try another time it may work. This is quite frustrating to have to try it over and over again to work. 
Am I doing anything weong?

**Comment by HuiiBuh** [comment]
Please fill the issue template otherwise I cannot help
