### ISSUE TITLE
Profile name not added in front of extracted pics when using "Control+s"

### ISSUE THREAD

**Issue by dante987** [HuiiBuh/InstagramDownloader#262]
When using "Control+s" properly (i.e. opening the post in a new tab), the extracted files don't have the profile name in front of them like when we download a single pic post.

Example:
Downloading "https://www.instagram.com/p/CXKQ86Dps0H/" we get
263871205_442938027268134_3664071965245975377_n
instead of
nasa_263871205_442938027268134_3664071965245975377_n

Can you please make it so that profile names are added in front ? :) Please

Device: Win10 pc
- Resolution: 4K
- Browser: Opera/Chrome/Firefox/Edge
- Extension Version: 4.5.5

**Comment by HuiiBuh** [comment]
This is allready tracked in #110
