### ISSUE TITLE
This extension does not give the highest quality on some pics (example inside)

### ISSUE THREAD

**Issue by dante987** [HuiiBuh/InstagramDownloader#264]
Unfortunately this extension does not give the highest quality on some pics.
Example:
Lets download an image say "https://www.instagram.com/p/d6rXmQIaCF/"

The downloaded image from this extension:
nasa_11352041_490745051076984_112814906_n
[18.6 kb 480x480]

Now if you download the same image from this site: "https://instafinsta.com/photo"
11352041_490745051076984_112814906_n
[59.6 kb 612x612]    ##higher quality##

Please look into this if possible. Please :)

Device: Windows 10 x64 pc
Resolution: 4k
Browser: Opera/Firefox/Edge (tested on all)
Extension Version: 4.5.5
__________________________________________________________________
Now I must also mention that most of the pics downloaded from this extension are better quality and resolution than any other site/extension out there.
Example:
Lets download an image say "https://www.instagram.com/p/CZ0aPeDtK5_/"

The downloaded image from this extension:
nasa_273693752_715558236076720_6843679969604858648_n
[429 kb 1440x1800]    ##higher quality##

Now if you download the same image from this site: "https://instafinsta.com/photo"
11352041_490745051076984_112814906_n
[325 kb 1080x1350]    

So thank you for that. Please don't change that. :)

**Comment by HuiiBuh** [comment]
Unfortunately I cannot improve the quality, as I already use the highest quality available.

I could reverse engineer the ig api, but this is not a step I am willing to take.
