### ISSUE TITLE
Stories are not saving as Instagram’s internal filename structure

### ISSUE THREAD

**Issue by christoarmani** [HuiiBuh/InstagramDownloader#265]
# Important: Issues without the following information will be closed

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to URL 'https://www.instagram.com/bugatti/' (or anyone's Story)
2. Click on '{user-profile} Story' 
3. See error any story that has a video and saves as a .mp4 gets this file format: "C4443EF39E2021F698D7EABE2E528AB0_video_dashinit"

**Expected behaviour**
The returned filename should appear like: "244176341_4365515556828422_265874683300281114_n"

**Screenshots**

**Device (please complete the following information):**
- Resolution: [3440x1440]
- Browser [Chrome]
- Extension Version [4.5.5]

**Additional context**
This started several months ago. I should have reported when I found it then.

**Comment by HuiiBuh** [comment]
I see that there is an issue here, but this is the file name ig gives me. 
I unfortunately don't have the time to fix this. If you want to fix it for me I am more that happy to merge the pr
