### ISSUE TITLE
Forcing the changelog tab to open when updating the plugin is a very bad decision

### ISSUE THREAD

**Issue by KarelWintersky** [HuiiBuh/InstagramDownloader#269]
**To Reproduce**
Just use an addon

Forcing the changelog tab to open when updating the plugin is a very bad decision. Not to mention that it is akin to intrusive advertising, it switches the tab, throws off the focus of perception and interferes with the work. 

**Expected behaviour**
plugin update notification on icon 

**Screenshots**
-- 

**Device (please complete the following information):**
Any browser version, 
4.6.1 version

**Comment by HuiiBuh** [comment]
I understand that you don't like This but it it the only source of income I can generate with the extension. As this extension needed lots of time to develop and maintain I see no other way (Perhaps you want to give e  a very sizable amount of money, so I don't have to ask any more ;) ) 
I could sell your data, display adds, etc but I think that that is also not great.

I should perhaps create a mechanism which ensures that the dialog does not open more than one a month

**Comment by KarelWintersky** [comment]
May be open dialog without focusing on it?
