### ISSUE TITLE
Downloaded Instagram "video" story (not image story) is of different quality on different screen resolutions [example inside]

### ISSUE THREAD

**Issue by dante987** [HuiiBuh/InstagramDownloader#270]
Downloaded Instagram "video" story (not image story) is of different quality on different screen resolutions [example inside]

I have a multi-monitor setup. 
Monitor 1 is 3840x2160 (4k)
Monitor 2 is 1440x900

Example:
www.instagram.com/stories/highlights/17927574161021260/
Downloading this in Monitor 1(4k) gives a file:
nasa_A646AE4AFC7A37D826A8AC555BBF2393_video_dashinit
Size: 356 kb
Data Rate: 280 kbps

Now downloading the same "video" story with the same browser just a different browser window on Monitor 2(1440x900) we get:
nasa_144AD29B5E4AA98E96A2D7591C5628B1_video_dashinit
Size: 594 kb
Data Rate: 475 kbps

Why does screen resolution change video quality ? 

Device: Windows 10 x64 pc
Resolution: 3840x2160 (4k), 1440x900
Browser: Opera/Firefox/Edge (tested on all)
Extension Version: 4.6.1

**Comment by HuiiBuh** [comment]
Because ig serves different resolutions for different screen sizes in order to save bandwidth

I will have a look if there is something I can do, but I think not....
