### ISSUE TITLE
No aparece  botón de descarga de historias en el navegador Google Chrome

### ISSUE THREAD

**Issue by ISMArtinz** [HuiiBuh/InstagramDownloader#274]
Recientemente, he descargado historias de Instagram, pero hace unas horas no me aparece el botón mencionado anteriormente.
He probado la misma extensión en otro navegador (Edge) y si sale el botón, el cual no sale en Google Chrome. ¿¿A qué se puede deber que no aparezca??

**Comment by HuiiBuh** [comment]
Please provide the information I requested in the issue template
