### ISSUE TITLE
Main feed and story downloads no longer available. 

### ISSUE THREAD

**Issue by Eikreis** [HuiiBuh/InstagramDownloader#275]
The buttons to download posts on the main feed are gone. 
I am also unable to download stories as the button is gone and the keyboard shortcut no longer appears to work. It doesn't matter if I access the stories through the main feed or the user's page.

Download buttons still appear and have also confirmed that keyboard shortcut works on individual user pages.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the main page URL 'https://www.instagram.com/'
2. Buttons to download are gone, unable to download stories.

**Expected behaviour**
Ability to download posts from the main feed directly through button or shortcut and download stories either with a button or shortcut.

**Device (please complete the following information):**
- Resolution: 4K
- Browser - Chrome
- Extension Version 4.6.1

**Comment by ISMArtinz** [comment]
> Es raro pero tengo 3 cuentas de IG y el bug solo aparece en una de ellas...
The same happens to me (Me pasa lo mismo).

**Comment by eudaldt** [comment]
Maybe it's a block from IG?

**Comment by Eikreis** [comment]
I'm not sure. I checked my other accounts as well and it seems that this issue only shows on my personal one (which I barely use the downloader on) whereas the account I would use for bulk downloading is completely fine. You would think if it's a block that it would affect that one... very strange.

**Comment by HuiiBuh** [comment]
That is totally normal. IG delivers different versions of its website to different accounts.
The new versions seems to have changed some stuff andy extension therfore cannot find the right place to insert the button.

If one of you can find the right query selector you can submit a pull request. Otherwise you have to wait until I get the new version and can fix this myself

**Comment by GitHub-Nate** [comment]
I'm having the exact same problem as OP at the same time he posted it. 

I have no clue where to find a "query selector" in order to "submit a pull request", sorry.

**Comment by eudaldt** [comment]
In my case now it works.

**Comment by GitHub-Nate** [comment]
> In my case now it works.

Same.

**Comment by Eikreis** [comment]
It also appears to be working now. Perhaps another new version came out that the existing code can handle. Appreciate everyone's comments and feedback!
