### ISSUE TITLE
Botón descargar no sale en historias ni en publicaciones recientes

### ISSUE THREAD

**Issue by ISMArtinz** [HuiiBuh/InstagramDownloader#276]
**To Reproduce**
No he podido hacer este paso 

**Screenshots**
![Captura de pantalla](https://user-images.githubusercontent.com/102067529/159359803-ad450317-064d-4014-bbce-890f47ea1b2f.png)
![Captura de pantalla 2](https://user-images.githubusercontent.com/102067529/159359840-1b2f9bd4-32c9-4892-b5e4-f0d679226dbf.png)

**Device PC (personal computer)
- Resolution: No lo sé
- Browser Chrome
- Extension Version 4.6.1

**Additional context**
Cuando abro Instagram con la extensión instalada, no me sale el botón de descargar la imagen, pero no solo no me sale ahí, sino que en las historias tampoco aparece. ¿¿A qué puede deberse esto??

PD: Sorry for not putting the rest in English, because the level I have is low.

**Comment by HuiiBuh** [comment]
Hi, 
unfortunately it is working for me. If you have some experience in web dev you can try to find out the correct query selectors and send me a pull request

**Comment by HuiiBuh** [comment]
Closing for #293
