### ISSUE TITLE
images saving as .webp instead of .jpg

### ISSUE THREAD

**Issue by katho0** [HuiiBuh/InstagramDownloader#277]
# Important: Issues without the following information will be closed

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to URL 'https://www.instagram.com/world_record_egg/'
3. See error

**Expected behaviour**
When I click the download button, I expect the file to download to my laptop and save as a jpeg but instead in the last week all images I try to save, download as .webp and then can not be opened. This only started happening in the last 2 weeks.

**Screenshots**
<img width="262" alt="Screen Shot 2022-03-23 at 8 58 31 pm" src="https://user-images.githubusercontent.com/102221279/159673107-83354112-25f4-4a33-ad9c-10e98563aac1.png">

**Device (please complete the following information):**
- Resolution: unknown
- Browser: chrome
- Extension Version: 4.6.1

**Additional context**
Pls help

**Comment by HuiiBuh** [comment]
In this case Ig changed the format.
There is nothing wrong with webp and I cannot transform it back to jpg...

**Comment by HuiiBuh** [comment]
Webp is just another image format.
Perhaps try to open it in the browser.
