### ISSUE TITLE
Failed to load extension File ~\Desktop\InstagramDownloader-master Error Manifest file is missing or unreadable Could not load manifest.

### ISSUE THREAD

**Issue by colorlol** [HuiiBuh/InstagramDownloader#281]
# Main issue is that the Manifest fie for some reason isn't found.

**Issue**
Since the extension is open source, I'm trying to change stuff up by myself for a little bit of fun but whenever I try to Load unpacked into chrome://extenions, It gives this error.
"Failed to load extension
File
~\Desktop\InstagramDownloader-master
Error
Manifest file is missing or unreadable
Could not load manifest."

I'm not really sure why. I didn't move any files or mess with the two manifest files. Am I doing something wrong or is there a fix?

**Comment by Hulth** [comment]
Readme says "Building in Windows is only partially supported." but without revealing further details, so maybe that's why you're running into issues?

**Comment by colorlol** [comment]
> Readme says "Building in Windows is only partially supported." but without revealing further details, so maybe that's why you're running into issues?

Ah I see, I think it's most likely because I'm still on Windows 10, will update now and update you on it.

**Comment by HuiiBuh** [comment]
You have to run `npm run build:dev` and then zip the chrome folder with the extension in it so the manifest is in the root folder of the zip
