### ISSUE TITLE
No descarga nada en Firefox

### ISSUE THREAD

**Issue by neoacevedo** [HuiiBuh/InstagramDownloader#282]
# Important: Issues without the following information will be closed

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to URL 'https://www.instagram.com/world_record_egg/'
2. Click on 'Download'
3. Nada pasa

**Expected behaviour**
Debería verse la descarga al lado de la barra de direcciones en Firefox

**Screenshots**

**Device (please complete the following information):**
- Resolution: FHD
- Browser: Firefox
- Extension Version 4.6.1

**Additional context**
```js
home [functions.ts:44:16](webpack://instagram_downloader/src/ts/functions.ts)
Image index:  -1 [functions.ts:44:16](webpack://instagram_downloader/src/ts/functions.ts)
SyntaxError: JSON.parse: unexpected keyword at line 1 column 1 of the JSON data
```

**Comment by HuiiBuh** [comment]
Did it start working for you again

**Comment by neoacevedo** [comment]
No, actually I try to download only one image, as always.

**Comment by topotech** [comment]
I just downloaded a full profile from Firefox yesterday, are you still having problems?

**Comment by neoacevedo** [comment]
No, for now it's downloading again.

**Comment by wetnun** [comment]
It hasn't worked for me since last Firefox update (currently on 100.0b4). Also running 4.6.1.

Only thing I get in my logs is an endless stream of `with timeout` errors from functions.ts:44:16 that has an empty array attached.

**Comment by wetnun** [comment]
Just upgraded to 100.0b7 and same result.

**Comment by wetnun** [comment]
It just started working again. No updates to plugin or firefox.  🤷

**Comment by HuiiBuh** [comment]
I would say that this is due to IG... I will close it for now as it seems to be working again for everyone
