### ISSUE TITLE
Saves Each Time to Desktop Instead of Last File Folder Accessed

### ISSUE THREAD

**Issue by KylePhoenix419** [HuiiBuh/InstagramDownloader#285]
Since downloading this extension, it's automatically saving everything to the Desktop by default. I can find no way to change this inside of the settings and - unlike other apps and such - it refuses to remain on the last file folder location. It automatically defaults back to the Desktop, which is fine for some of the files I download, but feel this is a "bug" since we can't designate that it go to the previous save location as most apps do, including many previous Instagram downloaders that I had before Google removed them from the WebStore.

**Comment by HuiiBuh** [comment]
I am afraid that I have no influence on where the photos get saved to.
