### ISSUE TITLE
Does bulk download only download from the main feed? 

### ISSUE THREAD

**Issue by GitHub-Nate** [HuiiBuh/InstagramDownloader#286]
I have recently noticed a bulk download got everything in the accounts feed; their photos, videos and the reels they had saved to their main feed. However, all the Videos and Reels not in their main feed weren't downloaded. Is this a known limitation of the extension? It can only download the main feed (aka everything under the "Posts" tab)?

**Comment by HuiiBuh** [comment]
Of you change the tab you can download the content there
