### ISSUE TITLE
Download media missing user profile name as file name on other PC

### ISSUE THREAD

**Issue by leoira** [HuiiBuh/InstagramDownloader#287]
I use this great Extensions
 for download the Instagram media in Chrome on PC A and PC B.
PC A and PC B Chrome version is same, 

Why PC A download media has user profile name as file name? 
(eg: s0on_ho_279275906_555800682609650_1671334977512823066_n.jpg)
However, PC B just has code file name?
(eg: 279275906_555800682609650_1671334977512823066_n.jpg)

How can and fix PC B problem?
What files I need to edit? Many thanks. 

I try to search on #110, but look like there is no fixed answer.

**Comment by HuiiBuh** [comment]
You will have to provide the extension version and the extension name for both PCs. Otherwise I cannot help...

**Comment by HuiiBuh** [comment]
And is it the same download method? If the first is the individual download and the second is bulk I cannot help you there
