### ISSUE TITLE
downloader stucks when the file is missing from the gallery

### ISSUE THREAD

**Issue by crossfire27** [HuiiBuh/InstagramDownloader#288]
# Important: Issues without the following information will be closed

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to URL 'https://www.instagram.com/vic_toryy/'
2. Click on 'download gallery up to 100 posts'
3. after downloading around 61% it stucks

**Expected behaviour**

Sometimes galleries have missing files usually videos and when trying to download singular file like this im getting note from the downloader that the file is missing, but when downloading gallery it stucks on this file and dont go further. 

**Screenshots**

**Device (please complete the following information):**
- Resolution: [not applicable]
- Browser [chrome]
- Extension Version [4.6.1]

**Additional context**

**Comment by HuiiBuh** [comment]
I do not have a button with download gallery up to 100 posts.
Can you send me the link to the extension you are using? I think it is a different one...

**Comment by crossfire27** [comment]
Sorry i wasn't precise enough, i click download gallery button and thats it, I manually stop downloading up to 100 or up to 200, there is no special button for this. I just want to tell that after downloading around 61 post from the top downloading will stop. 
https://chrome.google.com/webstore/detail/ig-downloader/cpgaheeihidjmolbakklolchdplenjai

**Comment by HuiiBuh** [comment]
OK in this case I will investigate :)

**Comment by HuiiBuh** [comment]
Bulk has been removed because IG blocked it completely. I will therefore close this issue
