### ISSUE TITLE
Download button no longer appearing

### ISSUE THREAD

**Issue by Gohzio** [HuiiBuh/InstagramDownloader#289]
# Important: Issues without the following information will be closed

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to URL 'https://www.instagram.com/world_record_egg/'
2. Click on image
3. No download button

**Expected behaviour**
I've been using this addon for a while now and no real issues. About 2 weeks ago now Instagram shuffled a few UI elements around and now the addon doesn't work, the shortcuts don't work there's no download button, nothing

**Screenshots**

**Device (please complete the following information):**
- Resolution: 2k (doesn't work on 1080p monitor either)
- Browser Firefox 95.0
- Extension Version 4.6.1

**Additional context**
I tried a couple of other addons expecting this one to be fixed quick but no one else has mentioned this issue but no other apps worked regardless

**Comment by AlbertArulPrakash** [comment]
This issue is going on for past 2-3 weeks. Not sure why

**Comment by HuiiBuh** [comment]
See #280.
And as I said there I cannot fix it if it is working for me. As soon as I have the same problem I will fix it. Unit then you could create a PR
