### ISSUE TITLE
ig downloaded extension grey out

### ISSUE THREAD

**Issue by mdidomenico4** [HuiiBuh/InstagramDownloader#292]
ever since i updated to Version 100.0.4896.127 (Official Build) (64-bit) of chrome, the IG downloader extension appears disabled.  when i click "extensions" (puzzle piece) the app shows greyed out, but it does seem to detect that it has full vs no access to ig pages vs other pages.  so it's doing something.  but unfortunately all the download icons on the pics disappeared as well.  up until the chrome update, the app was working fine

**Comment by HuiiBuh** [comment]
The greyed out part seems to have nothing to do with it being disabled. 
It seems like this should indicate that the extension does not offer and actions if you click the icon in the status bar. 

As for the icon not being visible see #280
