### ISSUE TITLE
Buttons not showing

### ISSUE THREAD

**Issue by Nissemus** [HuiiBuh/InstagramDownloader#293]
As of today, all the download buttons (picture, story) have disappeared from both Firefox and Chrome. 
Extension version 4.6.1.

**Comment by GitHub-Nate** [comment]
> As of today, all the download buttons (picture, story) have disappeared from both Firefox and Chrome. Extension version 4.6.1.

Same for me and I'll add that I removed the extension from Chrome and re-added it just to check and the issue still persists. No download buttons anywhere to be seen.

**Comment by GitHub-Nate** [comment]
> Glad to see I'm not the only one facing this issue but could not happen on a more worse day. Hope they fix the issue/bug soon. Any alternate recommendations?

Given that the time sensitive posts are stories, I believe https://www.storysaver.net/ does the trick and I think (not sure) it downloads the stories at the same quality IGDownloader does (source quality).

**Comment by mvandemar** [comment]
I just want to add that for some reason IG Downloader is grayed out for me on Chrome, even though it says it's active and has access to the site.

**Comment by philmcgowan** [comment]
Pretty much every downloader I've tried is not working in IG.

I'm guessing Meta updated code recently and might be potentially block all of these but I'm not a coder so I have no idea.

Hopefully fixed soon!

**Comment by mvandemar** [comment]
> Every downloader I've tried is not working in IG.
> 
> I'm guessing Meta updated code recently and might be potentially block all of these but I'm not a coder so I have no idea.
> 
> Hopefully fixed soon!

Online downloaders still work, although I have not tried any other addons. I am not sure it's possible to just "block" an extension, my guess is the html changed in such a way that the downloader can no longer parse the media links. That's just a guess though, I have not dug into the code.

**Comment by stvoidit** [comment]
IG в очередной раз обновили код сайта. раньше для удобства я использовал свои скрипты из консоли, но теперь они сильно изменили архитектуру фронтэнда.

**Comment by rlang4930** [comment]
it seems user based. it is still working on one of my accounts but not the other

**Comment by lordoffools** [comment]
> it seems user based. it is still working on one of my accounts but not the other

That's likely due to the changes not rolling out to you just yet. I expect it'll all be the same experience once that happens.

Now we just need someone to find out what changed, and adjust the downloader code to accommodate. Just a matter of time. :)

**Comment by Markussovic** [comment]
I have the same problem here. Hope it will be fixed soon. There's no other such great tool like IG Downloader.

**Comment by Gallyi** [comment]
Earlier today I had to deal with the same issues you guys described. My main account (which I only use do DL stuff on PC) was missing the download buttons. Switched to 2 other accounts and those worked fine. I proceeded to create more accounts on mobile (using my cell phone number) and then logging in on PC, but they were glitchy when switching back and forth between accounts. Some accounts I created displayed the download buttons while others didn't. Some showed the new Instagram site logo in the tab, others showed the old one. So I was trying to come up with a way to make things flawless when Instagram stopped letting me creating new accounts. Do you guys know if after a while the ''ban'' goes away? 
I was able to ''salvage'' some of the accounts that I ditched (the ones that didn't show the DL buttons) but I don't know if in the future I'll be able to create any more accounts since I created 6 or 7 accounts in a row :/

**Comment by GitHub-Nate** [comment]
I noticed yesterday, before the buttons disappeared on my main IG, and today that when I switch to my secondary account, which as of right now still has the IGDownloader buttons, they download as .webp files instead of .jpg.

**Comment by Markussovic** [comment]
I could live with that webp-problem as there's a little tool you can just copy into the folder, then doubleclick and all webp-files will get renamed into .jpg; the bigger problem is I can't download pictures anymore at all 😭😭

**Comment by stvoidit** [comment]
> Earlier today I had to deal with the same issues you guys described. My main account (which I only use do DL stuff on PC) was missing the download buttons. Switched to 2 other accounts and those worked fine. I proceeded to make more accounts on mobile (using my cell phone number) and then logging in on PC, but they were glitchy when switching back and forth between accounts. Some accounts I made had the download buttons while others didn't. Some showed the new Instagram site logo on the tab, others showed the old one. So I was trying to come up with a way to make things flawless when Instagram stopped letting me create new accounts. Do you guys know if after a while the ''ban'' goes away? I was able to ''salvage'' some of the accounts that I ditched (the ones that didn't have the DL buttons) but I don't know if in the future I'll be able to make any more accounts since I made 6 or 7 accounts in a day :/
> 
> UPDATE: I'm still able to use my cell phone number to verify all accounts (they were created on mobile, using the same number, but it's good) and even change passwords of the ones that I ditched. Still can't make new accounts. It's puzzling how some accounts created today show the download buttons while others don't. Shouldn't the extension affect all accounts equally? Bummer.

It's normal that you have different versions of the site on different accounts. IG can conduct A/B tests, or give a new version selectively. Most likely, they will introduce the current version, which breaks the extension, since the architecture of the code has become noticeably more complicated there, I could not find where they hide links to data received from XHR requests (spoiler: you can still use the network query analysis tool and there are familiar json objects with direct links to photos and videos).

**Comment by Gallyi** [comment]
>which make it impossible at the moment to download content.
It's not. Read my post. I have 4 accounts that still show the DL button and can download stories/images etc. I've tested them all right before replying to you. It's just puzzling to me that out of the 6 or 7 accounts that I have, only those 4 are able to download content. And they were all created today (supposedly after the source code changes took place).

**Comment by Markussovic** [comment]
> It's not. Read my post. I have 4 accounts that still show the DL button and can download stories/images etc. 

This doesn't help us who don't have multiple accounts of which some are not changed yet.

**Comment by thinkpad4** [comment]
@HuiiBuh I hope you are able to fix this soon, I love this extension and can't live without it.  Thank you

**Comment by Markussovic** [comment]
> @HuiiBuh I hope you are able to fix this soon, I love this extension and can't live without it. Thank you

Same here. I used and need it every day 😥

**Comment by miffusa** [comment]
> @HuiiBuh I hope you are able to fix this soon, I love this extension and can't live without it. Thank you

Yes please! I love this extension and depend on it greatly.

**Comment by jcafowler** [comment]
Depending on your comfort with dev tools, you can use the inspect on chrome then toggle over to network to see what you want to grab. Media tab will grab videos and then img grabs pics. You can use the little circle with the line through it to clear it out if it gets too crowded. Right click the content to open it in a new tab and then you can download it smoothly

**Comment by malaysia9012** [comment]
same here. apparently  chrome is having issues now...I am testing all links now

**Comment by Gallyi** [comment]
UPDATE: Extension still working properly as of today. I'm not an expert and I don't know how long this is gonna last, but it's still working. Stories, images, videos, you name it. 
Now, I had to create new accounts after the supposed code change. And even while creating new accounts one has to be careful as to not to be ''redirected'' to the old Instagram. For example, yesterday I was making new accounts but I saved the people I follow like Chrome bookmarks. Some accounts ended up without the download button (the bookmarks had the old IG logo).
I first created the accounts through the IG app on mobile using my phone number and then logged in on PC. 
I'm not trying to look smart here, I don't know if this is going to last, but if someone is desperately looking for a short-term solution, there you go.

**Comment by lordoffools** [comment]
It's not "working again."

The changes Instagram rolled out are rolling out in phases. Some accounts are in scope, some are not yet. Eventually 100% plus all new accounts will be impacted.

This bug is still a bug.

**Comment by Gallyi** [comment]
Another update: Yup, it seems that the button's gone for good. An hour ago all my active accounts still had the button, but now it's gone and when I switch between accounts I have to refresh the page in order to really log in with the other account while before it was a smooth transition.

**Comment by Hawkeye131** [comment]
Bump

**Comment by Hello-Its-Dave** [comment]
Good to know I'm not the only one that lost access to IG Downloader.  Buttons do not show and the extension is greyed out in Opera (using Chrome installer).  I hope there is a fix to this soon.

**Comment by tomnapp2** [comment]
Bump

**Comment by Gallyi** [comment]
Instagram without this extension just sucks. It'd be great if this could be fixed soon, but I'm sure it's hard to keep up with IG's changes.

**Comment by lordoffools** [comment]
Any contributors / owners around and digging into this? No rush, obviously, just curious to know if this is being worked on actively?

Thank you!!

**Comment by malaysia9012** [comment]
the owner so quiet on this
lost interest? quit already?

**Comment by GitHub-Nate** [comment]
> the owner so quiet on this lost interest? quit already?

I think it's a one man operation, can't imagine he/she makes any money from it and it's been a day. Let's not get aggressive. We have alternatives (https://www.storysaver.net for Stories and lots of options for DL'ing posts) they are just less convenient. We can survive with those until he/she is able to fix the bug.

**Comment by lordoffools** [comment]
> > the owner so quiet on this lost interest? quit already?
> 
> I think it's a one man operation, can't imagine he/she makes any money from it and it's been a day. Let's not get passive aggressive. We have alternatives (https://www.storysaver.net for Stories and lots of options for DL'ing posts), they are just less convenient. We can survive with those until he/she is able to fix the bug.

Completely agree! We're all very appreciative.

**Comment by malaysia9012** [comment]
so for now need to use online downloader till he /she  fix the bug

**Comment by malaysia9012** [comment]
yeah need to use online downloader for now.... but all of you go try open incognito the instagram and see the download signal is there or not. if its not there, is app issue
but if its there, its accountb issue

**Comment by Gallyi** [comment]
>yeah need to use online downloader for now

Yeah, but it's incredibly inconvenient.
 
>but all of you go try open incognito the instagram and see the download signal is there or not. if its not there, is app issue
but if its there, its accountb issue

I think everyone in this thread can attest to the fact that Instagram messed up the extension, it has nothing to do with accounts being shadow banned. I've tested it and some accounts that were brand new earlier today still had the DL button, but all of a sudden it vanished.

**Comment by aliares2010** [comment]
So finally can we use this extension anymore? or we must find another extension or totally another way?

**Comment by malaysia9012** [comment]
> > yeah need to use online downloader for now
> 
> Yeah, but it's incredibly inconvenient.
> 
> > but all of you go try open incognito the instagram and see the download signal is there or not. if its not there, is app issue
> > but if its there, its accountb issue
> 
> I think everyone in this thread can attest to the fact that Instagram messed up the extension, it has nothing to do with accounts being shadow banned. I've tested it and some accounts that were brand new earlier today still had the DL button, but all of a sudden it vanished.




today I tried open incognito
the download button this there

so what happen

**Comment by malaysia9012** [comment]
open incognito the download button is there...so somehow the error in ig

**Comment by aliares2010** [comment]
> open incognito the download button is there...so somehow the error in ig

I just tried on incognito and the it did not work there too!
and online downloaders are not good enough!

**Comment by helloabella** [comment]
Here to bump this thread! Hope it'll get fixed soon.

**Comment by malaysia9012** [comment]
if I open ig incognito w,o loggin in
the button is there

**Comment by amuagarwal** [comment]
it look like chrome changed the extension policy to access site data because of it the ig downloader not able to read site data for instagram

**Comment by malaysia9012** [comment]
> it look like chrome changed the extension policy to access site data because of it the ig downloader not able to read site data for instagram

but edge also same, cannot open ig downloader
so its ig issue

**Comment by amuagarwal** [comment]
> > it look like chrome changed the extension policy to access site data because of it the ig downloader not able to read site data for instagram
> 
> but edge also same, cannot open ig downloader so its ig issue

but its Chromium  based browser so it apply to all no matter one is using chrome or not even i am using Brave and it not working

**Comment by malaysia9012** [comment]
welll the deveoper need to fix it quickly

**Comment by GitHub-Nate** [comment]
> welll the deveoper need to fix it quickly

Or what, you'll demand a refund for the free extension you use? Chill out and stop posting unless you're adding something helpful. 

Use the alternatives until it's fixed and be thankful that the creator, for FREE, even built this extension. Not to mention he/she will likely soon fix the bug and get it working again. Less ungratefulness please.

**Comment by malaysia9012** [comment]
btw I think its not fully extension problem. I tested yesterday night (Malaysia time)

chrome- not wokring
edge- this morning stop working.

but incognito for
chrome and edge shows the download symbol

so its like instagram account connection to app, chrome extension issue

**Comment by aliares2010** [comment]
> > welll the deveoper need to fix it quickly
> 
> Or what, you'll demand a refund for the free extension you use? Chill out and stop posting unless you're adding something helpful.
> 
> Use the alternatives until it's fixed and be thankful that the creator, for FREE, even built this extension. Not to mention he/she will likely soon fix the bug and get it working again. Less ungratefulness please.

can you suggest any alternative? not online downloaders

**Comment by HuiiBuh** [comment]
I just pushed an update which should fix most of the issues. 
Unfortunately I had to remove the bulk downloader and the hover downloader because they where not incompatible with IG and there was no way to implement them now. 

So if it is working after the newest update please close this issue.

**Comment by malaysia9012** [comment]
> I just pushed an update which should fix most of the issues. Unfortunately I had to remove the bulk downloader and the hover downloader because they where not incompatible with IG and there was no way to implement them now.
> 
> So if it is working after the newest update please close this issue.


so its the stupid instagram issue then

okay we will test it

**Comment by HuiiBuh** [comment]
The fixed version is v4.6.2

**Comment by malaysia9012** [comment]
but google chrome  review still ppl complaining

how to update?

**Comment by HuiiBuh** [comment]
@malaysia9012 
Of course it is an IG issue. I did not change anything for the last 3 month. 
But IG changes stuff around and sometimes this breaks things. And it more than likely that IG serves different version of their app to every one of us, so there is another problem and the reason why some stuff works for you on some does not

**Comment by amuagarwal** [comment]
> but google chrome review still ppl complaining
> 
> how to update?

wait for sometime it took time to reflect new version in chrome store

**Comment by malaysia9012** [comment]
instagram update broke all extensions
and chrome extension couldn't communicate well

and there you go, all fall

**Comment by malaysia9012** [comment]
> > but google chrome review still ppl complaining
> > how to update?
> 
> wait for sometime it took time to reflect new version in chrome store



how about edge?
is different section right?

**Comment by amuagarwal** [comment]
> > > but google chrome review still ppl complaining
> > > how to update?
> > 
> > 
> > wait for sometime it took time to reflect new version in chrome store
> 
> how about edge? is different section right?

edge also share chrome store for extension with own extension store

**Comment by malaysia9012** [comment]
owh I thought edge one store
chrome one store
thanks  @amuagarwal

**Comment by malaysia9012** [comment]
> > owh I thought edge one store chrome one store thanks @amuagarwal
> 
> basically there are only two stores
> 
> 1. Firefox store
> 2. Chrome Store
>    any chromium base browser can use chrome store or one store provided by browser developer

microsoft edge under which category?

**Comment by amuagarwal** [comment]
Ch

> > > owh I thought edge one store chrome one store thanks @amuagarwal
> > 
> > 
> > basically there are only two stores
> > 
> > 1. Firefox store
> > 2. Chrome Store
> >    any chromium base browser can use chrome store or one store provided by browser developer
> 
> microsoft edge under which category?

Chromium

**Comment by lordoffools** [comment]
Updated via Chrome Store. Works perfectly for me now. Thanks so much for fixing this, @HuiiBuh. You have our support!

**Comment by ferindel8783** [comment]
It seems to be working now after updating to v4.6.2. Thanks a lot for your reactivity, @HuiiBuh

**Comment by lordoffools** [comment]
Ah, I see that videos are not downloading, only photos. Photos work perfectly for me now.

**Comment by JAKware** [comment]
It is working for me.  I'm not able to download video from the main feed window.  Get a message that IG doesn't allow it any longer.

Ideas on what to use to download those videos?

**Comment by Nissemus** [comment]
> I just pushed an update which should fix most of the issues. Unfortunately I had to remove the bulk downloader and the hover downloader because they where not incompatible with IG and there was no way to implement them now.

Working for me, so closing this issue. Thank you! 👍

**Comment by HuiiBuh** [comment]
Videos are a hit ore miss....

**Comment by lordoffools** [comment]
> Videos are a hit ore miss....

I see. Sadness. :(

They used to work 100% of the time for me prior to IG's latest changes.

**Comment by stvoidit** [comment]
> 

the latest update does not make a download fix, it makes it possible to display the button ANYWAY. IG has seriously changed the front code, so we are waiting for more releases.
https://github.com/HuiiBuh/InstagramDownloader/compare/v4.6.2...master#diff-380959ba5dfb49e14f0ddf07087464f19dae859411766fd9a2f3a7a96e119308

**Comment by stvoidit** [comment]
@Nissemus I see you have closed this issue, the latest update solves it directly, but downloading photos and videos still does not work. Are you working on this problem?

**Comment by GameDevNinja** [comment]
> I just pushed an update which should fix most of the issues. Unfortunately I had to remove the bulk downloader and the hover downloader because they where not incompatible with IG and there was no way to implement them now.
> 
> So if it is working after the newest update please close this issue.

awesome dude been trying to find a way that I could support your work, and saw the optional paypal thing after latest update , keep up the good work.

**Comment by lordoffools** [comment]
> Nissemus

Indeed, I would reopen this.

**Comment by stvoidit** [comment]
> @Nissemus I see you have closed this issue, the latest update solves it directly, but downloading photos and videos still does not work. Are you working on this problem?

Very strange, now downloads are working again... wtf IG

**Comment by malaysia9012** [comment]
have u try and confirm again?

**Comment by malaysia9012** [comment]
tested, wokring for chrome for now

**Comment by malaysia9012** [comment]
> > I just pushed an update which should fix most of the issues. Unfortunately I had to remove the bulk downloader and the hover downloader because they where not incompatible with IG and there was no way to implement them now.
> 
> Working for me, so closing this issue. Thank you! 👍


microsoft edge still not wokring

**Comment by epicstar7** [comment]
Working in Firefox now, but noticed when saving stories, filename says _unknown_***_ instead of the beginning with the username.

**Comment by Gallyi** [comment]
Thank you very much for your quick fix! 👍👍👍 
If that's too much to ask, is there a way, in the future, to download pics (not from stories, from regular posts) with the same resolution as before? Right now it seems that 1080 x 1350 is the maximum resolution while before it was possible to download at least 1440 x 1800.

**Comment by HuiiBuh** [comment]
@Gallyi unfortunately I have not found a way to make high res downloads possible again

**Comment by lordoffools** [comment]
Are the high res images even still available? I'm not seeing a way to manually pull them, myself, so I don't see how the Chrome extension could do it...

I might be missing something, though.

**Comment by jcafowler** [comment]
@Gallyi I'm pretty sure the res is determined by the image uploaded. I've found different resolutions for different images across the board. I would try downloading one of the images from something you already know to be high res and see if the resolutions are different.

**Comment by JAKware** [comment]
> > @Gallyi I'm pretty sure the res is determined by the image uploaded. I've found different resolutions for different images across the board. I would try downloading one of the images from something you already know to be high res and see if the resolutions are different.
> 
> I just downloaded an IG post (pic) that I had DL'ed using the extension before it broke. The previous version was 1440x1467 and the new version is 1080x1100.
> 
> So it seems either IG lowered the resolution of the pictures they store or the extension isn't pulling the highest res version available. The two website based downloaders I just tried pulled the same size (1080x1100) version.
> 
> edit: just for good measure I used 'Inspect > Network' on the post and depending on how you view the post, there's a small version and a large version of the picture and the large is also 1080x1100.
> 
> edit2: I noticed when trying to DL videos and reels that a pop-up says the extension can't because IG started blocking it. However, just FYI, when using website based downloaders they can still DL videos and reels so it is possible. The website downloaders get versions a tiny bit lower in quality but same resolution and nearly identical compared to the version I DL'ed with this extension before IG changed and it broke.

Can you suggest web based downloaders, I'm using storysaver.net (Download Instagram Videos) and it spins for a few seconds, then nothing.  

Thanks in advance.

**Comment by HuiiBuh** [comment]
To clear some things up.
The image resolution is determined by the quality ig processes and the quality ig sends to you the user.

Before the update I could take advantage an open api, but now this has been patched and I can only parse the html. There I look for the highest resolution and download it afterwards

**Comment by lordoffools** [comment]
> To clear some things up. The image resolution is determined by the quality ig processes and the quality ig sends to you the user.
> 
> Before the update I could take advantage an open api, but now this has been patched and I can only parse the html. There I look for the highest resolution and download it afterwards

+1

That's been my observation too from just digging through the code right now (just simply inspecting elements, etc).

Do we know what the issue is with video downloads? Did they change how they deliver the video to the client?

**Comment by GitHub-Nate** [comment]
> Can you suggest web based downloaders, I'm using storysaver.net (Download Instagram Videos) and it spins for a few seconds, then nothing.

I just tested it and it works for me. I hit download then solve the captcha, wait 2-3 seconds and the stories show up. I don't have any experience with other sites so I don't have any to recommend. Sorry. 

> To clear some things up.
The image resolution is determined by the quality ig processes and the quality ig sends to you the user.

> Before the update I could take advantage an open api, but now this has been patched and I can only parse the html. There I look for the highest resolution and download it afterwards

This is a massive bummer because I assume there is no workaround. We're just going to be DL'ing lower quality pictures from IG from now on... lame.

**Comment by Nissemus** [comment]
I've noticed that the Firefox version of the updated extension sometimes randomly downloads a different picture from the one you request. This happens often enough to be annoying.

**Comment by GitHub-Nate** [comment]
Just downloaded a picture and video story with the extension and then the same ones with StorySaver.net and here's the differences: 

Story saver: 

Pic from Stories: 1170x2080 - 237kb
Vid from Stories: 720x1280 - 1.26mb

From extension: 

Pic from Stories: 750x1333 - 141kb
Vid from Stories: 480x854 - 633kb

So at least for now, Storysaver.net is downloading Stories at a much higher quality for both pic and video stories.

**Comment by Gallyi** [comment]
@GitHub-Nate I've tried that too. Let me also add that instadownloader.co (I'm not advertising by any means), is capable of downloading normal pics found in the profile with a res of 1440 x 1799.
Either way, we should be thankful that HuiiBuh has fixed the issue and that this amazing extension is working again.

**Comment by GitHub-Nate** [comment]
> I've tried that too. Let me also add that instadownloader.co (I'm not advertising by any means), is capable of downloading normal pics found in the profile with a res of 1440 x 1799.

Good catch. That site is downloading pictures at the res the extension did before IG changed and the extension broke. I just downloaded a pic using that site that I had downloaded using the extension a week ago. Identical. So that site, somehow, is able to find and download the high-res versions still.

**Comment by malaysia9012** [comment]
when I tried download , it says couldn't find post.
but the post of the user is there after I open their profile.... 
ols advice

**Comment by malaysia9012** [comment]
edge still not updated? still cannot use

**Comment by thinkpad4** [comment]
Edge is Chrome based, you know this right?  Just use the Chrome extension

**Comment by Gallyi** [comment]
I don't know if it's just me, but it seems that the extension is already downloading stories at the same resolution it used to before it stopped working 👍👍👍
Now, all it's missing for the extension to be absolutely perfect is being able to download normal pics at high res again.

**Comment by GitHub-Nate** [comment]
> I don't know if it's just me, but it seems that the extension is already downloading stories at the same resolution it used to before it stopped working 👍👍👍 Now, all it's missing for the extension to be absolutely perfect is being able to download normal pics at high res again.

Just tested it and it isn't. Downloaded a pic and video from someones Stories and then downloaded them using https://www.storysaver.net/ and the extension pulled lower quality versions of both. 

I don't think that will change until the extension gets worked on and given the owners post about him not enjoying it anymore, quitting and wanting someone else to take over, I imagine he isn't working on it to bring back full functionality. He'll let whoever takes over do that. But the extension won't magically work fully without being worked on.

**Comment by Nissemus** [comment]
It's still randomly downloading the wrong pic for me every few times.

**Comment by malaysia9012** [comment]
> Edge is Chrome based, you know this right? Just use the Chrome extension

still not wokring for edge

**Comment by Nissemus** [comment]
This has just got ridiculous now. The extension constantly downloads the wrong image and downloads an image instead of a video. The thing is unusable. To have the developer bail at this point is disappointing to say the least.

**Comment by Gallyi** [comment]
My only issues so far is the extension not downloading pics at the res it used to and saving pics/videos as ''unknown''. Let's be a little more grateful...

**Comment by GitHub-Nate** [comment]
> This has just got ridiculous now. The extension constantly downloads the wrong image and downloads an image instead of a video. The thing is unusable. To have the developer bail at this point is disappointing to say the least.

Again, this extension is FREE. Get off it. If the dev lets someone else take over hopefully it gets fixed but at worse it's not working anymore. Sad but not "ridiculous" considering YOU USE IT FOR FREE.

**Comment by GameDevNinja** [comment]
hm says IG started blocking download of videos although some other apps can still download it, if possible hope the dev can fix the video download too
