### ISSUE TITLE
4.6.2 breaking IG on Firefox

### ISSUE THREAD

**Issue by BlackEye2k** [HuiiBuh/InstagramDownloader#297]
After updating to 4.6.2 the IG feed isn't loading anymore in Firefox (101.0). Disabling the plugin "resolves" this issue.

![2022-06-02_134221](https://user-images.githubusercontent.com/22717671/171622308-72396a75-1bda-4747-b369-d8e4459b18a3.jpg)
.

**Comment by HuiiBuh** [comment]
It is working without a problem for me. Please provide the information described in the bug report issue template
