### ISSUE TITLE
Cannot save at highest quality?

### ISSUE THREAD

**Issue by ikeyoshi** [HuiiBuh/InstagramDownloader#298]
Hello!
I am not good at English so sorry if my expression is wrong.

With this update to v4.6.2, I can now download images.
I appreciate it very much.
But then the question arose.

Until the update, I saved images from the Elements Panel in the Developer Tools.
The size of the saved image was 1170 x 2080.
However, InstagramDownloader saves images at 750 x 1333.
This led me to believe that InstagramDownloader may not be downloading at the highest quality.

Am I wrong?
Or does InstagramDownloader have room for improvement?

**Comment by HuiiBuh** [comment]
Sry nothing I can do. IG changed something
