### ISSUE TITLE
The filename from Stories start with "unknown"

### ISSUE THREAD

**Issue by ikeyoshi** [HuiiBuh/InstagramDownloader#299]
The filename from Posts start with the username.
(For example, username_12323453_39560772365_23894507049476863_n.jpg)

However, filename from Stories start with "unknown".
(For example, unknown_12323453_39560772365_23894507049476863_n.jpg)

Is it just me, or is this a problem?

**Comment by HuiiBuh** [comment]
There is currently no way to find the right user name...
If you find a fix send a PR my way
