### ISSUE TITLE
Version 4.6.2 issues like lower resolution images, "unknown" in front of the filename, Videos cannot be downloaded

### ISSUE THREAD

**Issue by dante987** [HuiiBuh/InstagramDownloader#302]
Version 4.6.2 did bring back the download option but there are some issues:

1) The downloaded images are of lower resolution now. 
Example: https://www.instagram.com/p/CeMF18zuJBG/
This pic which I downloaded yesterday (Version 4.6.1) was 1439x1373 665kb.
Today (Version 4.6.2) its just 1080x1350 271kb.

2) Downloaded story videos have "unknown" in front of the filename instead of profile name.

3) Video posts show "Videos cannot be downloaded, because IG started blocking it."

**Device:**
- Resolution [4K]
- Browser [Opera]
- Extension Version 4.6.2

**Comment by HuiiBuh** [comment]
All these issues are limitations that where introduced in order to block tools like this. Im afraid that I cannot change anything...
