### ISSUE TITLE
The extension was removed from chrom store

### ISSUE THREAD

**Issue by amuagarwal** [HuiiBuh/InstagramDownloader#361]
The extension was removed from chrome store and chrome extension manager showing "This extension violates the Web Store policy.", any clues

**Comment by FryingPanBrock** [comment]
The last version on the store was 4.12.5 from October 2023. The Github repository should be updated. It would be a good idea to provide a Chrome build of the extension that people can custom install, in case reuploading the extension to the Chrome store doesn't succeed.

**Comment by amuagarwal** [comment]
I am not sure how there is the version diff. here and chrome store

**Comment by kschwerin** [comment]
For Edge its forcefully disabled as containing Malware.

**Comment by amuagarwal** [comment]
I think this is becase of "File System Access API"

**Comment by kschwerin** [comment]
The question is who is thenew maintiner?

**Comment by kschwerin** [comment]
The question is who is the new maintiner?

**Comment by amuagarwal** [comment]
Someone is there else it hard to find the version diff the chrome version which was removed is 4.12.5 and here repo saying 4.6.3

**Comment by kschwerin** [comment]
Yes, but they are clearly not maintaining it here.

**Comment by karanb192** [comment]
[4.12.5_0.zip](https://github.com/igdownloader/InstagramDownloader/files/13845539/4.12.5_0.zip)
Extract this zip file -> Open chrome://extensions in your chrome browser -> Enable developer mode using toggle button -> Drag and drop this folder with name '4.12.5_0' into chrome -> Extension is installed!

**Comment by kschwerin** [comment]
> [4.12.5_0.zip](https://github.com/igdownloader/InstagramDownloader/files/13845539/4.12.5_0.zip) Extract this zip file -> Open chrome://extensions in your chrome browser -> Enable developer mode using toggle button -> Drag and drop this folder with name '4.12.5_0' into chrome -> Extension is installed!

It is installed for me, but Edge instantly disables it and does not allow it to be re-enabled. 
![image](https://github.com/igdownloader/InstagramDownloader/assets/50388098/13f3a2d0-1afb-4a5c-90b9-840f11194bdb)

**Comment by 19h** [comment]
jfyi that latest zip file above is tracking every single interaction via both Google Analytics and Sentry, haven't read through the entire code yet though

**Comment by Rocket3192** [comment]
Guess the new maintainer wasn't a good person to pick

**Comment by igdownloader** [comment]
Hey all, thanks for reaching out and sorry you've been dealing with this issue.

IG Downloader has been reinstated on the Chrome Web Store.

**Comment by FryingPanBrock** [comment]
I know this issue is closed, but I discovered IG Downloader has a website run by the new maintainer. It's probably a good place to look in case of future problems:
https://ig-downloader.com/

**Comment by kschwerin** [comment]
> I know this issue is closed, but I discovered IG Downloader has a website run by the new maintainer. It's probably a good place to look in case of future problems: https://ig-downloader.com/

NordVPN doesnt trust it as having malicious code on it
![image](https://github.com/igdownloader/InstagramDownloader/assets/50388098/b861cd8a-ac0e-4314-8918-af2afd1bf6f4)
