### ISSUE TITLE
Naming suggestions for files

### ISSUE THREAD

**Issue by Halvar10** [HuiiBuh/InstagramDownloader#38]
Just a suggestion:

When I start a download of a single image or video, a file dialog pops up for naming it. If it's a video, "video.mp4" is prefilled as a name, and if it's an image, it's "image.jpg". I think this isn't the most practical solution, because it means I almost always have to rename the file in the dialog before saving it. I'd prefer the solution where the name is prefilled with instagram's picture GUID name, because a) it allows me to download quickly and rename later, and b) i get a warning if I already downloaded the same file, so as long as I have not renamed them I won't get duplicate files.

**Comment by HuiiBuh** [comment]
Fixed in the next commit

**Comment by HuiiBuh** [comment]
Could you verify that the story download is working for you in with v2.0 before I upload the new version to the Mozilla Webiste?

**Comment by Halvar10** [comment]
Thank you for working on this!

Story download is working for me now with 1.6.1 and Firefox 67.0.4. I wonder if it was a local problem or if Instagram changed anything. I had emptied my browser caches before reporting the bug, unsuccessfully.

Laugh about me, but I don't know how to build the .xpi for v2.0. How do I get the META-INF folder? I can probably read up on that, but I will need a few days.

**Comment by HuiiBuh** [comment]
Ok. Its good that this is working in the latest released version. Then there is no reason you should try to install it... 

Just if you wanted to know how its done:
For this you don´t have to build anything. Just download the firefox.zip from [v2.0](https://github.com/HuiiBuh/InstagramDownloader/releases) (or any other extension) and extract it. After that you can visite the `about:debugging` page in firefox and click on the `load addon temporarily` button and open the `manifest.json` form the extracted firefox folder.

**Comment by Halvar10** [comment]
Thanks! ++

**Comment by sdushantha** [comment]
I just downloaded the add on for Firefox but the image still has the name `image.png`.
As @Halvar10 suggested, using the image GUID would be smarter.

**Comment by HuiiBuh** [comment]
It is different in the dev Branche.
I have to test a bit more and then it will be updated.
