### ISSUE TITLE
Tip: Choose whether to download only photos or video (or both)

### ISSUE THREAD

**Issue by procobain** [HuiiBuh/InstagramDownloader#39]
I believe it helps in download time, I believe that many are not interested in videos.

**Comment by HuiiBuh** [comment]
So you only want to download the preview picture of the video if I am correct?

**Comment by procobain** [comment]
I'm not talking about the thumb of a video, I'm talking about only photo, or just video.

Example, some people have 500mb of photos, and 1GB of videos, this slows the download a lot, I would like to have the option to download only the 500mb of photos.

Thank you (I'm using a translator, maybe it sounds strange)

**Comment by HuiiBuh** [comment]
So you are referring to the action that takes place after you click the `download all` button?
