### ISSUE TITLE
I'm hesitant to click "download all"

### ISSUE THREAD

**Issue by saucefrog** [HuiiBuh/InstagramDownloader#46]
If I click this button on an Instagram account, will the add-on immediately download hundreds of images into the root of my download folder, or will it create a subfolder first?

**Comment by HuiiBuh** [comment]
Ok I think I should be more clear in my description. The download all button will create a ZIP file in which all the images are saved. Only the zip file will be saved. 
If you are planning on downloading that many images plan to wait a while ;D, but it shoud work. 
Please report back if everything worked accordingly

**Comment by HuiiBuh** [comment]
Added more description to the modal and the readme #51
