### ISSUE TITLE
can't download all the photos of an instagram account

### ISSUE THREAD

**Issue by SpectyteCovelight** [HuiiBuh/InstagramDownloader#59]
Hey, I really enjoy you extension I've installed on firefox on Mac 
but i'm having problems when I try to download all the pictures of a profile
 
I just click the " download all " button and did not start to downloading 

I hope your answer, thanks in advance

**Comment by HuiiBuh** [comment]
I am glad that you enjoy my extension. 
Thank you for reporting the issue. I think some buttons in the popup are hidden, so you can't start the download. 

I will fix this in the next couple of days. If you still want to download all images (before I fix it) search in the bottom right corner of the popup and click if your cursor turns into a pointer :D

**Comment by SpectyteCovelight** [comment]
Hey It's working again!! thanks for fixed it, you're the best! 
my best wishes and keep developing wonderful things

**Comment by HuiiBuh** [comment]
#60
