### ISSUE TITLE
Download button doesn't work in opened picture

### ISSUE THREAD

**Issue by jedikalimero** [HuiiBuh/InstagramDownloader#62]
The download button doesn't work when looking at an individual picture page or when opened from the gallery of an account. The download button that appears in the gallery thumbnails works and also the "download all" button at the top of the gallery. It is only the button to the right of the opened picture the one that doesn't work.
I can still use the button in the thumbnail to download the desired image, but when there are several images in a post, it only downloads the first image, so it is a partial workaround.

![Captura de pantalla 2019-11-27 17 43 55](https://user-images.githubusercontent.com/18701653/69747364-284cfc80-113e-11ea-8c8e-be6e94da65fa.png)
![Captura de pantalla 2019-11-27 17 43 43](https://user-images.githubusercontent.com/18701653/69747380-30a53780-113e-11ea-9f1c-2bf98e4e9843.png)

**Comment by HuiiBuh** [comment]
Fixed in #63 
Please verify if the bug was fixed.

**Comment by jedikalimero** [comment]
Yes! it worked! :-)
