### ISSUE TITLE
Invalid Url

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [HuiiBuh/InstagramDownloader#71]
After downloading all images from a page, it opened a new tab starting with `blob:moz-extension://0298ced2-b18e-3f48-...` but It shows invalid url and nothing downloads

**Comment by ThinkDigitalSoftware** [comment]
update, this works fine in regular, but not in privacy browsing

**Comment by HuiiBuh** [comment]
Yes I am afraid that the bulk download does not work in the private mode

**Comment by ThinkDigitalSoftware** [comment]
Ok. Thanks!

**Comment by HuiiBuh** [comment]
Hey good news for your request. 
I managed to get the private bulk download working ;D

**Comment by ThinkDigitalSoftware** [comment]
Awesome! Thank you very much!
