### ISSUE TITLE
Instagram Downloader 2.2.6 for Firefox Android no Longer Downloads as of 2/18/2020

### ISSUE THREAD

**Issue by mindwarp42** [HuiiBuh/InstagramDownloader#72]
As of February 18, 2020, Instagram Downloader 2.2.6 for Firefox no longer downloads any media from Instagram. There are multiple reports of this from the add-on's review page. The download button does appear, but is non-functional. In my case, this is on Firefox Android 68.5.0, running on a stock, unrooted Moto G7 running Android 9 Pie patched through the December 2019 patch (current for a stock Moto G7). I did try uninstalling and reinstalling the add-on, but nothing changed.

**Comment by f0rr357** [comment]
same here, 19/02/20 firefox 73.0.1 (64 bit), windows 10

**Comment by f0rr357** [comment]
same here, post lateral button doesn't work. 19/02/20 firefox 73.0.1 (64 bit), Windows 10. Frontal post button works, probem for multiple post images tho.

**Comment by HuiiBuh** [comment]
Hey thanks for the report. 
I try to look into it this afternoon

**Comment by HuiiBuh** [comment]
Could confirm the issue just now. 
I think that Instagram has changed their class names. Should be relatively easy to fix

**Comment by HuiiBuh** [comment]
Hey I just fixed it and uploaded a new version.
Please verify if it is working again.

**Comment by superfreeman1989** [comment]
> 
> 
> Hey I just fixed it and uploaded a new version.
> Please verify if it is working again.

Awesome! Working now. Thank you!

**Comment by HuiiBuh** [comment]
Your welcome

**Comment by f0rr357** [comment]
yes thank you!
