### ISSUE TITLE
doesn't download all pictures/videos

### ISSUE THREAD

**Issue by rotnemmoc** [HuiiBuh/InstagramDownloader#78]
When a post has multiple pictures/videos, one (perhaps more for some posts) doesn't download. For example, for this post https://www.instagram.com/p/B9GNUzdnTDL/ picture #5 isn't downloading, instead, it redownloads picture #1.

**Comment by HuiiBuh** [comment]
Thanks for the Report. 
I am not sure if it is possible to get all pictures but I will look into it soon

**Comment by HuiiBuh** [comment]
I just had a quick Look at the api and it is possible.  
I just dont know when I will have the time to fix this.

**Comment by HuiiBuh** [comment]
Hey I just had a Look at the Code and tried it myself.
Did you trie it again to confirm the error?

**Comment by rotnemmoc** [comment]
For me, the same link https://www.instagram.com/p/B9GNUzdnTDL/ has a new weird behaviour: photos 1, 4 & 5 download but photos 2 & 3 don't, the extension button seems to have no effect.

**Comment by HuiiBuh** [comment]
OK it looks like Instagram change a hole lot the last few days.
I am currentely working an an improved 3.0 which will (hopefully) fix all issues. Because of the current Situation I hope that I will finish the refactoring until the end of the week.

**Comment by HuiiBuh** [comment]
Hey please check out the newest Version. Everything should be fixed
