### ISSUE TITLE
Filename on multiposts

### ISSUE THREAD

**Issue by cschleter** [HuiiBuh/InstagramDownloader#79]
When there is a multi-post (eg., multiple photos posted as a group with the white multi-post icon in the upper right corner), the downloaded file for the first item posted is named correctly (the numeric portion of the filename is unique) but the second and third photos download a second and third copy of the first photo (with the same filename). I did see one instance where there were 5 photos posted, I downloaded the first and second items (they downloaded with the same name) then the 4th one which had a different name. I also had one with 4 photos. The first 3 downloaded with the same name and the 4th was a different filename.

The behavior is not consistent as I also saw a post with 7 items, the first two duplicated but the remaining items had unique names. Not sure exactly what is going on. If I use Firefox Inspector, the links display each photo with a unique name.

**Comment by HuiiBuh** [comment]
Could you pleasesend me an example Post so I can trie it with this Post?

**Comment by cschleter** [comment]
Try this one:

https://www.instagram.com/p/B9rE8M2l3sR/ 
<https://www.instagram.com/p/B9rE8M2l3sR/>

The first photo in the group downloads to the correct filename 
(suzharrison71_894608862539572322855491878102868529776286n.jpg).

The second photo in the group (the headshot) downloads a second copy of 
the first photo with the same name as the first photo plus a sequence 
number indicating a duplicate filename 
(suzharrison71_894608862539572322855491878102868529776286n(1).jpg).

Using Inspector in Firefox to find the actual photo link in the source, 
the filename for the second photo should be 
suzharrison71_894647735603866479060708183911295270601082n.jpg.

The remaining photos in the group appear to download correctly.

I can probably find other examples if you need them. Also, if any of 
this doesn't make sense, let me know and I'll try to explain it better.

Thanks!

**Comment by HuiiBuh** [comment]
Fixed it

**Comment by cschleter** [comment]
Thanks but, actually, it's not 100% fixed. It works for some in a set 
but not others.

Here's one where the 3rd one duplicates the 2nd (the first 2 are correct)
https://www.instagram.com/p/B82Bx_tpk_8/
The 3rd one should be 
cloverhempz_8497898726029874597998765942884049860223238n.jpg.

Same thing in this one
https://www.instagram.com/p/B9xPUY-Jqow/
The 3rd one should be 
cloverhempz_89749964290717095243241363074489558694728n.jpg.

Here's one where the 1st one works but the 2nd one doesn't
https://www.instagram.com/p/B9CsAWyJF-G/
The 2nd one should be 
tianahtucker_8757752425831593219321204958317575262535152n.jpg.

Here, the 4th one duplicates the 3rd one
https://www.instagram.com/p/B9r8QVfpy_H/
The 4th one should be 
skinnyminniequeen_893870051150056101097171431130170913577336n.jpg

Here, the 5th one duplicates the 4th one (the first 4 are correct)
https://www.instagram.com/p/B9xTSJspFK6/
The 5th one should be 
skinnyminniequeen_899434581052674025115929839998599210206949n.jpg

The thing that's weird is that the behavior is not consistent.

Thanks for looking into this. I love the tool and am happy to help try 
to swat bugs.

**Comment by cschleter** [comment]
Win 10 PC 1600x900.

**Comment by cschleter** [comment]
Firefox 74.0 64-bit

**Comment by HuiiBuh** [comment]
Thanks. I will look into it in about a week

**Comment by HuiiBuh** [comment]
Hey please check out the newest Version. Everything should be fixed
