### ISSUE TITLE
Download image preview for video Story (for exemple image with music)

### ISSUE THREAD

**Issue by DDRRDD** [HuiiBuh/InstagramDownloader#96]
Hello,

For story with music, Instagram create a mini video.mp4 with the still image.
I prefer to download the still image from the preview with is sometime better quality and less size than the .mp4
With Firefox I do that with <Ctrl>+I > Media to find the Video and the still image

It can be cool to make this download available with an other button.
And/or with a setting in the plug-in option : "Download Video : only MP4 / only JPG / MP4 + JPG"

Thanks for your great work on this plug-in
Best Regards,
David
France

**Comment by HuiiBuh** [comment]
If you know a way in which I could differentiate a video from a picture which is a video I am willing to implement it. 

I am however not willing to add a second button (and select a icon for video and a icon for image download) for this feature. It is just to much work especially as I do not even use this extension actively. 

If you want to you can create a pull request and add this yourself.
