### ISSUE TITLE
ts format????

### ISSUE THREAD

**Issue by shahinesi** [HuiiBuh/InstagramDownloader#97]
![image](https://user-images.githubusercontent.com/16535600/90731093-757d8980-e2de-11ea-8466-85e52ee0adb8.png)

**Comment by HuiiBuh** [comment]
It seems like my build script has failed. 
I will fix this soon

**Comment by shahinesi** [comment]
> It seems like my build script has failed.
> I will fix this soon

tnx

**Comment by shahinesi** [comment]
> It seems like my build script has failed.
> I will fix this soon

hi
do you fix?

**Comment by HuiiBuh** [comment]
I have submitted the extension.
It is not not up to me when the extension gets released

**Comment by shahinesi** [comment]
> I have submitted the extension.
> It is not not up to me when the extension gets released

What?

**Comment by HuiiBuh** [comment]
The extensions get reviewed by an employee of the Chrome/Firefox store. It is not up to me to decide when the review is done

**Comment by HuiiBuh** [comment]
Should be fixed now
