### ISSUE TITLE
Not working in Firefox Fenix (Android)

### ISSUE THREAD

**Issue by jaytohe** [HuiiBuh/InstagramDownloader#99]
When hitting the download button nothing happens both in stories and posts.

In order to test this out use [this](https://github.com/interfect/fenix/) Fenix fork which allows installation of more extensions that those available in Mozilla's recommended program. 

[Here's](https://addons.mozilla.org/en-US/firefox/collections/16175324/my-fenix-addons/) my custom addon collection which includes this addon. To point Firefox to it and install the add-on follow [this](https://github.com/interfect/fenix/pull/50#issuecomment-685187265).

Fixing this now will make it easier when Mozilla finally decides to allow installation of this addon.

**Comment by HuiiBuh** [comment]
I don't think that I will fix the addon until Firefox supports mobile Addons again.
I am however willing to review a pull request if you want to fix the bug

**Comment by HuiiBuh** [comment]
I will close this issue until there is some development in firefox mobile.

**Comment by Smart123s** [comment]
The issue should be related to https://github.com/mozilla-mobile/fenix/issues/16585
